### DISCUSSION TITLE
Created: Datepicker Component

### DISCUSSION THREAD

**Discussion by rikgirbes** [saadeghi/daisyui#1004] [Ideas / feature requests]
I created a Datepicker component working with DaisyUI.

All vanilla typescript, although it does use date-fns and floating-ui.

Of course this is both not "css only" and uses 2 libraries.

Thus the question can this be of any use for the project?
Or should I release it separately?

![dark](https://user-images.githubusercontent.com/12097579/179357321-73ca48d7-9232-4271-8ad7-4633a9235ca2.png)
![light](https://user-images.githubusercontent.com/12097579/179357322-4b51321a-a692-4f50-8ef1-656dc2e2a345.png)
![cyberpunk](https://user-images.githubusercontent.com/12097579/179357318-1ddc3e10-4cd1-4e9b-9646-ae63300159c6.png)

**Comment by saadeghi** [comment]
That's amazing! Many people asked for this.  

Yes, I think you should release it as a separate package.  
If the npm package is ready for production and the docs is straightforward, I will add a link to it on daisyUI docs as well. I'm thinking about adding a "plugins" section on the sidebar of daisyUI document website.

Let me know if you have any questions ✌️

**Reply by rsessine** [reply]
Hi @saadeghi any news on the plugin section?

**Reply by saadeghi** [reply]
Yes: https://github.com/saadeghi/daisyui/discussions/1004#discussioncomment-11472407

**Comment by tonyYo00** [comment]
I would like a plugin based on daisyUI and more headless combinations like react-table + daisyUI. Or some common components like rc-component + daisyUI

**Comment by tonyYo00** [comment]
1. Core: Tailwind + DaisyUI Config 
2. Plugin:
   1. Headless : react-table, react-hot-toast, react-modal
   2. Other: rc-component/tree rc-component/date-picker   rc-component/cascader    react-select or rc-component/select  ....

@saadeghi  Do we have some plugin schedules?

**Comment by saadeghi** [comment]
@tonyYo00 daisyUI only provides the style. So any UI library that is "headless" (only provides functionality + does not provide design decisions or it's optional) can work well with daisyUI.  
There could be wrapper packages to include 2 in 1 but of course those should be separate project with their own npm package.

**Comment by rikgirbes** [comment]
@tonyYo00 as for the schedule: will probably release the date-picker in 1-2 weeks (lots of work on daily job 😄 )

**Comment by tonyYo00** [comment]
@rikgirbes  i found a headless lib about date: https://github.com/its-danny/use-lilius , I think we can build a daisyUI-exentention with headless: 
table: [react-table](https://tanstack.com/table/v8)
select: [downshift](https://github.com/downshift-js/downshift)
date-picker: [use-lilius](https://github.com/its-danny/use-lilius)
toast: [react-hot-toast](https://react-hot-toast.com/)

**Comment by rikgirbes** [comment]
@tonyYo00 not really that headless though..

Also would be React-only.

And uses date-fns in the background, and popperjs for floating.

I made a Vanilla-Ts version, that uses Datefns also, and floating-ui for the floating functionality (which is a treeshakeable version of popper you could say)

I think that would more fit daisyui as it can be injected in all frameworks (e.g. react/vue/svelte etc), or just in vanilla js/ts.

I haven't found the time yet to make a release-able package, although the code is done and functional. (apart from some small refactoring maybe)

**Comment by rikgirbes** [comment]
Also toast are now in DaisyUI (atleast the styles for it), making a js lib for handling toast is easy enough, no need to only support react.

**Comment by ThatXliner** [comment]
> I haven't found the time yet to make a release-able package, although the code is done and functional. (apart from some small refactoring maybe)

I'm eager to try it. Publishing a GitHub repo is a good start.

Also, this issue should be made into a [discussion](https://github.com/saadeghi/daisyui/discussions)

**Reply by saadeghi** [reply]
I moved this issue to discussions. thank you

**Comment by tonyYo00** [comment]
We say extention or plugin is to target some specific areas, if the scope and daisy exactly the same, then why daisy not directly implement it? If some components have some complex state logic, in order to adapt to all the framework, I worry that it is not conducive to style modification

**Reply by saadeghi** [reply]
daisyUI only provides the UI design, not functionality.  
I wish there was a way to apply design decisions to browser's native date picker input but it's not possible. Therefore, there are JS packages to simulate the date picker functionality using divs and buttons.

**Reply by wuarmin** [reply]
In my opinion it is the only right decision to let daisyUI be a pure design framework.

**Reply by rikgirbes** [reply]
Yeah well, all styles for the date-picker are written in .scss using the tailwind @apply functionality.
E.g. uses all the available daisyUI classes (btn / bg / etc.)

Thats why it goes along with the Themes daisyUI provides.

If @saadeghi  would allow JS etc in the daisyui framework, it would get bloated, and not easily maintainable.
Thus the idea with Plugins is probably the best way to go.
Keep daisyUI design only; use plugins for functionality but using the daisyUI classes etc.

Although it might be a good idea to write some doc/guidelines/rules for how plugins should be made.
E.g.: vanilla only, using only tailwind/daisyUI classes, not interfering with other basic styling, etc etc.

**Reply by rikgirbes** [reply]
For reference, this is current (un-refactored) scss:

```scss
@layer components {
    .datepicker,
    .datepicker-from,
    .datepicker-to {
        &.dp {
            @apply hidden z-10 bg-base-200 p-2 shadow text-base-content absolute top-0 left-0;
            border-radius: var(--rounded-box);
            [data-dp-arrow] {
                @apply absolute bg-inherit rotate-45 w-2 h-2;
            }
            .datepicker-header {
                @apply flex gap-1 border-b border-base-300 pb-1 mb-1;
                > div {
                    @apply flex-1 flex items-center justify-center;
                }
                > button {
                    @apply btn btn-sm btn-ghost;
                }
            }
            .datepicker-week-days {
                @apply grid grid-cols-7 border-b border-base-300 pb-1 mb-1;
                > div {
                    @apply text-center font-bold text-xs;
                }
            }
            .datepicker-days {
                @apply grid grid-cols-7;
                .datepicker-day {
                    @apply btn btn-xs btn-ghost;
                    &.datepicker-day-other-month {
                        @apply opacity-60;
                    }
                    &.datepicker-day-disabled {
                        @apply opacity-60 bg-transparent;
                    }
                    &.datepicker-day-selected {
                        @apply btn-primary;
                    }
                    &.datepicker-day-today:not(.datepicker-day-selected) {
                        @apply text-accent;
                    }
                }
            }
        }
        &[data-open] {
            &.dp {
                @apply block;
            }
        }
    }
}
```
