### DISCUSSION TITLE
What is the correct way to use own height(size) for default buttons/ input etc ?

### DISCUSSION THREAD

**Discussion by Kens-Jaswal** [saadeghi/daisyui#1238] [Q&A] [answered]
Can anyone elaborate what is the correct way to edit default sizes behaviour for daisyUI components following as (using tailwind along with):

I mean I have own size for all these components, who should I change them, best way to change with variable but how or giving them own required classes in app.css?
```css
/* default components dimensions  */

.btn {
  height: 3rem;   min-height: 3rem;
}

.btn-sm {
  height: 2rem;   min-height: 2rem;
}

.btn-lg {
  height: 4rem;   min-height: 4rem;
}

.btn-xs {
  height: 1.5rem;   min-height: 1.5rem;
}

.btn-circle {
  height: 3rem; width: 3rem;
}

.btn-square {
  height: 3rem; width: 3rem;
}
```
kindly help
