### DISCUSSION TITLE
How to overide collapse transitions?

### DISCUSSION THREAD

**Discussion by zed-wong** [saadeghi/daisyui#1423] [Q&A] [answered]
I've got 4 lines of content inside `collapse-content`, and the transition wasn't smooth, but I can't apply the `transition: height 1s` to `collapse-content`, is there a way I can override it to make the toggling look consistent and smooth? Thanks in advance.

**Comment by saadeghi** [comment, marked as answer]
This is unfortunately a limitation of CSS. We can't animate height value from `0` to `auto` so what's happening here is just a transition for padding and background color (in case it has a background color)

This is the CSS we're using:
```css
.collapse-content {
  /* ... */
  transition: padding .2s ease-in-out,background-color .2s ease-in-out;
}
```
And you can change the duration like this
```css
.collapse-content {
  /* ... */
  transition: padding 1s ease-in-out,background-color 1s ease-in-out;
}
```
But it really can't be smooth because we can't animate the height (because we don't know what is the maximum height of content) and we can just animate padding to create an illusion of animation.

Let me know if you have any questions
