### DISCUSSION TITLE
Code mockup expand

### DISCUSSION THREAD

**Discussion by PerryFinn** [saadeghi/daisyui#1494] [Ideas / feature requests]
Add color to the three points in the header of the Code mockup component, and set the header title.

just like this:
![image](https://user-images.githubusercontent.com/72293244/211156684-a9a83fe4-7f7c-47c9-8a51-3206c58fd82c.png)

**Comment by saadeghi** [comment]
Here's how you can do it for your own project:  
https://play.tailwindcss.com/sjWY7UcO9i?file=css
```css
.mockup-code {
   @apply pt-14;
}
.mockup-code:before {
  @apply absolute right-24 top-5 opacity-100;
  box-shadow: 1.4em 0 #FF6158, 2.8em 0 #FFC02E, 4.2em 0 #24CA41;
}
```
```html
<div class="mockup-code m-10">
  <div class="absolute top-3 left-6">Title</div>
  <pre data-prefix="$"><code>npm i daisyui</code></pre>
</div>
```

But if your asking it to be the default style for everyone, I don't think that's a good idea.

Let me know if you have any questions.
