### DISCUSSION TITLE
Enhance radial progress

### DISCUSSION THREAD

**Discussion by xudaotutou** [saadeghi/daisyui#1589] [Ideas / feature requests]
I think that we can expose start angle and end angle control shape
![image](https://user-images.githubusercontent.com/71751336/218250747-cc55c5c9-31aa-43cb-8203-aba2ed82d920.png)
This is implementation of my idea

**Comment by saadeghi** [comment]
Can you please provide a code example?

**Reply by xudaotutou** [reply]
> Can you please provide a code example?

![image](https://user-images.githubusercontent.com/71751336/221567497-1bc35196-2d2a-4602-9f96-d0023d1ba204.png)
That's what it looks like.

**Comment by xudaotutou** [comment]
- I use plenty of  `calc` , but I don't know if there's bad performance
``` css
.radial-progress {
    position: relative;
    display: flex;
    align-items: center;
    justify-content: center;
    border-radius: 9999px;
    --value: 40;
    --thickness: 10;
    --size: 10rem;
    --start: 180;
    --end: 360;
    --range: calc(var(--end) - var(--start));
    --percentage: calc(var(--value) / 360 * var(--range) * 1%);
    --content-col: blue;
    --content-n-col: red;
    --ball-col: black;
    --bar-r: calc((var(--thickness) / 4 + 0.5) * 1%);
    width: var(--size);
    height: var(--size)
}
.radial-progress::after,
    .radial-progress::before {
    position: absolute;
    border-radius: 9999px;
      content: ""
}
.radial-progress::before {
    top: 0px;
    right: 0px;
    bottom: 0px;
    left: 0px;
      background: radial-gradient(
            farthest-side,
            var(--ball-col) 95%,
            transparent
          )
          top/calc((var(--thickness) + 2)/ 2 * 1%)
          calc((var(--thickness) + 2) / 2 * 1%) no-repeat,
        conic-gradient(
          var(--content-col) var(--percentage),
          transparent var(--percentage),
          transparent calc(100% + var(--percentage)),
          var(--content-n-col) calc(100% + var(--percentage))
        );
      -webkit-mask: radial-gradient(
        farthest-side,
        transparent calc(98% - var(--thickness) * 1%),
        rgb(0, 0, 0) calc(99% - var(--thickness) * 1%),
        rgb(0, 0, 0) 99%,
        transparent 100%
      );
      mask: radial-gradient(
        farthest-side,
        transparent calc(98% - var(--thickness) * 1%),
        rgb(0, 0, 0) calc(99% - var(--thickness) * 1%),
        rgb(0, 0, 0) 99%,
        transparent 100%
      );
      transform: rotate(calc(calc(var(--start) - 180) * 1deg))
}
.radial-progress::after {
    z-index: 10;
      inset: calc(50% - var(--bar-r));
      background: radial-gradient(
        farthest-side,
        var(--ball-col) 95%,
        transparent
      );
      transform: rotate(
          calc(
            var(--value) * var(--range) * 0.01deg + var(--start) * 1deg + 90deg
          )
        )
        translate(calc(var(--size) / 2 - 50%))
}
```
