### DISCUSSION TITLE
SVG icons in steps

### DISCUSSION THREAD

**Discussion by m40ma0** [saadeghi/daisyui#1639] [Q&A] [answered]
Hi, as stated in the title, how do I add svg icons inside steps data content?

```
<ul class="steps steps-vertical text-sm">
  {#if info.type === 'call'}
	  <li data-content="📞" class="step">
	  </li>
  {:else if info.type === 'comment'}
	  <li data-content="✏️" class="step">
	  </li>
  {:else if info.type === 'email'}
	  <li data-content="✉️" class="step">
	  </li>
  {/if}
</ul>
```

I want to insert lets say, 
```
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="h-4 w-4">
<path
	stroke-linecap="round"
	stroke-linejoin="round"
	d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L6.832 19.82a4.5 4.5 0 01-1.897 1.13l-2.685.8.8-2.685a4.5 4.5 0 011.13-1.897L16.863 4.487zm0 0L19.5 7.125"
/>
</svg>
```
this svg into data content. How do i do this?

**Comment by saadeghi** [comment, marked as answer]
`steps` is using `:before`/`:after` pseudo elements for cleaner HTML so it's not possible to put a `<svg>` tag in it but you can put a SVG file as the background like this: https://play.tailwindcss.com/MTT9ROaqm4?file=css
```css
.step-icon-keyboard:after{
  background-repeat: no-repeat;
  background-position: center;
  background-image: url("https://raw.githubusercontent.com/google/material-design-icons/master/src/hardware/keyboard/materialiconsoutlined/24px.svg");
}
```
```html
<ul class="w-full steps">
  <li class="step">Step 1</li> 
  <li data-content="" class="step step-icon-keyboard">Step 2</li>
  <li class="step">Step 3</li>
</ul>
```
Related issue: https://github.com/saadeghi/daisyui/issues/442

**Reply by m40ma0** [reply]
Hi, im using hero icons but this way, the icons arent reactive to light/dark mode (i.e. icon stays black in dark mode). How can this be fixed?

**Reply by saadeghi** [reply]
In that case, you can do this:  
https://play.tailwindcss.com/kT9705RN2U?file=css
```css
.steps .step svg {
    z-index: 2;
    grid-column-start: 1;
    grid-row-start: 1;
}
```
This style 👆 moves the SVG icon to the circle area
```html
<ul class="w-full steps">
  <li class="step">Step 1</li> 
  <li data-content="" class="step">

    <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24"><path d="M0 0h24v24H0V0zm0 0h24v24H0V0z" fill="none"/><path d="M20 7v10H4V7h16m0-2H4c-1.1 0-1.99.9-1.99 2L2 17c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V7c0-1.1-.9-2-2-2zm-9 3h2v2h-2zm0 3h2v2h-2zM8 8h2v2H8zm0 3h2v2H8zm-3 0h2v2H5zm0-3h2v2H5zm3 6h8v2H8zm6-3h2v2h-2zm0-3h2v2h-2zm3 3h2v2h-2zm0-3h2v2h-2z"/></svg>

    Step 2
    
  </li>
  <li class="step">Step 3</li>
</ul>
```
Let me know if you have any questions
