### DISCUSSION TITLE
Is it possible to add tooltips to radio button groups?

### DISCUSSION THREAD

**Discussion by douglaslassance** [saadeghi/daisyui#1641] [Q&A] [answered]
Expectedly, the following HTML will not work.

```html
<div class="btn-group">
  <div class="tooltip" data-tip="hello">
    <input type="radio" name="options" data-title="A" class="btn" checked />
  </div>
  <input type="radio" name="options" data-title="B" class="btn" />
  <input type="radio" name="options" data-title="C" class="btn" />
</div>
```

Would love to know how this can be achieved.

**Comment by saadeghi** [comment, marked as answer]
Unfortunately this combination was not predicted and I can't change it now because it will break existing apps... But it will be fixed in the next major version (v3.0)  

For now, you can apply these changes and make it work: https://play.tailwindcss.com/mbIdvDlmll?file=css
```css
.btn-group .btn{
  @apply inline-flex;
}
.btn-group input:checked + .btn {
    border-color: hsl(var(--p));
    background-color: hsl(var(--p));
    color: hsl(var(--pc));
}
.btn-group .btn:first-of-type:not(:last-of-type) {
    border-top-left-radius: var(--rounded-btn, 0.5rem);
    border-top-right-radius: 0;
    border-bottom-left-radius: var(--rounded-btn, 0.5rem);
    border-bottom-right-radius: 0;
}

.btn-group .btn:last-child:not(:first-of-type) {
    border-top-left-radius: 0;
    border-top-right-radius: var(--rounded-btn, 0.5rem);
    border-bottom-left-radius: 0;
    border-bottom-right-radius: var(--rounded-btn, 0.5rem);
}
```
```html
<div class="btn-group m-20">
  
  <input type="radio" name="options" data-title="A" id="a" class="hidden" checked />
  <label class="tooltip btn" data-tip="hello" for="a">
    A
  </label>

  <input type="radio" name="options" data-title="B" id="b" class="hidden" checked />
  <label class="tooltip btn" data-tip="hello" for="b">
    B
  </label>

  <input type="radio" name="options" data-title="C" id="c" class="hidden" checked />
  <label class="tooltip btn" data-tip="hello" for="c">
    C
  </label>
  
</div>
```
Let me know if you have any questions
