### DISCUSSION TITLE
Add a way to reverse lifted tab

### DISCUSSION THREAD

**Discussion by Suniron** [saadeghi/daisyui#1643] [Ideas / feature requests]
Hi there,

I need a way to reverse the lifted tab 💡
https://daisyui.com/components/tab/#lifted

It's for a mobile navbar 🙄
![image](https://user-images.githubusercontent.com/36677774/221604021-23526b48-14f5-49ba-9c47-b316b19ff0e7.png)

**Comment by saadeghi** [comment]
This style doesn't exist in daisyUI now, but you can customize it like this:   
https://play.tailwindcss.com/SYK0C5zTmd?file=css
```css
.tab-lifted {
  border-top-color: var(--tab-border-color);
  border-width: var(--tab-border, 1px) 0 0 0;
  border-top-left-radius: 0;
  border-top-right-radius: 0;
  border-bottom-left-radius: var(--tab-radius, 0.5rem);
  border-bottom-right-radius: var(--tab-radius, 0.5rem);
  padding-top: 0;
  padding-bottom: var(--tab-border, 1px);
}

.tab-lifted.tab-active:not(.tab-disabled):not([disabled]) {
    background-color: var(--tab-bg);
    border-width: 0 var(--tab-border, 1px) var(--tab-border, 1px) var(--tab-border, 1px);
    border-bottom-color: var(--tab-border-color);
    border-top-color: var(--tab-border-color);
    padding-bottom: 0;
    padding-top: var(--tab-border, 1px);
}
.tab-lifted.tab-active:not(.tab-disabled):not([disabled]):before, .tab-lifted.tab-active:not(.tab-disabled):not([disabled]):after {
    top: 0;
}

.tab-lifted.tab-active:not(.tab-disabled):not([disabled]):before {
    --circle-pos: bottom left;
}
.tab-lifted.tab-active:not(.tab-disabled):not([disabled]):after {
    --circle-pos: bottom right;
}
```
