### DISCUSSION TITLE
Can you modify the default border radius for all themes

### DISCUSSION THREAD

**Discussion by killjin** [saadeghi/daisyui#2018] [Ideas / feature requests]
Can you modify the default border radius for all themes？

**Comment by saadeghi** [comment]
There are 3 CSS variables for border radius as you can see here:  
https://daisyui.com/docs/themes/#-5
```
--rounded-box
--rounded-btn
--rounded-badge
```

And these CSS variables have different values on each theme like this (in CSS file)

```css
[data-theme=light] {
  --rounded-box: 1rem;
  --rounded-btn: 0.5rem;
  --rounded-badge: 1.9rem;
}
```

So you can modify each theme from the config or from the CSS file.  
Or if you want a faster but dirtier way, you can set the value for everything using a higher CSS specificity like this (in CSS file)
```css
:root {
  --rounded-box: 1rem !important;
  --rounded-btn: 0.5rem !important;
  --rounded-badge: 1.9rem !important;
}
```
