### DISCUSSION TITLE
Can I use this library with shadcn/ui?

### DISCUSSION THREAD

**Discussion by ManuRodgers** [saadeghi/daisyui#2140] [Q&A] [answered]
Can I use this library with shadcn/ui?

**Comment by saadeghi** [comment, marked as answer]
As far as I know there's no problem.  

You can use some components from daisyUI and some other components from other libraries.  
In case there's conflict with class names (both libraries apply styles to the same class name) you can use the `prefix` config of daisyUI to add a specific prefix to all daisyUI class names and avoid style conflicts.

Let me know if you have any questions.

**Reply by ManuRodgers** [reply]
Thanks mate for quick response

**Reply by prashantbhudwal** [reply]
@ManuRodgers If you are using a theme in daisy ui, using both together is not so straightforward, you have to maintain both themes.

Also, if you are using daisy, running shad init will deleted all daisy config, any globals, and existing plug-ins in tailwind, you will have to manually resolve it like a merge conflict.

Learned it the hard way.

**Reply by edxeth** [reply]
@prashantbhudwal how did you configure a daisyUI theme altogether with shadcn/ui? The two together are creating conflict because they share `:root`, can you please explain to us how do you make it work and how do you mantain the themes?

**Reply by prashantbhudwal** [reply]
I just hacked. Made sure that everything is same in both. Hassle a first time and then you just forget about it and keep extending shad.

**Reply by edxeth** [reply]
@prashantbhudwal do you mind sharing your globals.css and tailwind.config.js setup for daisyUI and shadcn/ui? So that I can understand it better. I'm new to this and kinda slow as well lol

EDIT: I've managed to get it working with `cssVariables` set to `false`, but that's not what I want. I'm currently switching theme via daisyUI's theme controller component and sadly shadcn/ui doesn't recognize the theme switching action to dark although I've set `darkMode: ["class", '[data-theme="dark"]']` in my `tailwind.config.ts`. The question is how do I get `cssVariables` to work with daisyUI dark theme?

EDIT2: It seems that the above method is the best approach, we should stick to `cssVariables` set to `false`, that's the way!

**Comment by miilord** [comment]
If you want to use DaisyUI's color themes in ShadcnUI, you can try the following methods:

1. Set `"cssVariables": true` in `components.json`
2. Remove the color utility classes of ShadcnUI in global.css
3. Try this code in `tailwind.config.js`
```javascript
const daisyuiColorObj = require('daisyui/src/theming/index')
...
theme: {
    ...
    extend: {
      colors: {
        border: daisyuiColorObj['base-content'],
        input: daisyuiColorObj['base-content'],
        ring: daisyuiColorObj['base-content'],
        background: daisyuiColorObj['base-100'],
        foreground: daisyuiColorObj['base-content'],
        primary: {
          DEFAULT: daisyuiColorObj['primary'],
          foreground: daisyuiColorObj['primary-content'],
        },
        secondary: {
          DEFAULT: daisyuiColorObj['secondary'],
          foreground: daisyuiColorObj['secondary-content'],
        },
        destructive: {
          DEFAULT: daisyuiColorObj['error'],
          foreground: daisyuiColorObj['error-content'],
        },
        muted: {
          DEFAULT: daisyuiColorObj['base-300'],
          foreground: daisyuiColorObj['base-content'],
        },
        accent: {
          DEFAULT: daisyuiColorObj['accent'],
          foreground: daisyuiColorObj['accent-content'],
        },
        popover: {
          DEFAULT: daisyuiColorObj['base-100'],
          foreground: daisyuiColorObj['base-content'],
        },
        card: {
          DEFAULT: daisyuiColorObj['base-100'],
          foreground: daisyuiColorObj['base-content'],
        },
      },
      borderRadius: {
        lg: 'var(--rounded-btn)',
        md: 'calc(var(--rounded-btn) - 2px)',
        sm: 'calc(var(--rounded-btn) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
```
![WX20240202-181035@2x](https://github.com/saadeghi/daisyui/assets/30593788/53b35986-1394-4205-a867-792cd28030e5)

**Reply by NayamAmarshe** [reply]
What about the default ShadCN theme?

**Reply by miilord** [reply]
I'm not sure, this might not be a good practice because shadcn uses fewer colors than daisyui

**Reply by NayamAmarshe** [reply]
I'd like to use DaisyUI themes with ShadCN components. So I thought it'd be good to also have the ShadCN theme along with the default DaisyUI themes.

**Reply by AbirSantra** [reply]
Thank you this worked wonders!

**Comment by Zegoverno** [comment]
Hey, I would like to use shadcn components but using the themes and style from daisyUI, any one could make is work?

**Reply by NayamAmarshe** [reply]
We just did it in https://github.com/upscayl/upscayl

You can take a look :)

**Reply by Zegoverno** [reply]
Thank you for sharing!

**Reply by n0acar** [reply]
I made a tool for this. Check it out :) 

App: https://www.nevy.me/tiny/daisy-to-shadcn
All the themes: https://github.com/n0acar/tiny-projects/blob/main/src/app/daisy-to-shadcn/local.css

**Comment by CHC383** [comment]
For anyone who is looking for solution on DaisyUI v5 with Tailwind CSS v4, see the context in https://github.com/saadeghi/daisyui/discussions/3246#discussioncomment-11837367, and you could have code like below in your CSS file for the colors and adjust them accordingly:

```CSS
@theme {
  --color-border: var(--color-base-content);
  --color-input: var(--color-base-content);
  --color-ring: var(--color-base-content);
  --color-background: var(--color-base-100);
  --color-foreground: var(--color-base-content);

  --color-card: var(--color-base-100);
  --color-card-foreground: var(--color-base-content);

  --color-popover: var(--color-base-100);
  --color-popover-foreground: var(--color-base-content);

  /** --color-primary (xxx-primary) is already defined in DaisyUI theme */
  --color-primary-foreground: var(--color-primary-content);
  --color-secondary-foreground: var(--color-secondary-content);
  --color-accent-foreground: var(--color-accent-content);

  --color-muted: var(--color-base-300);
  /** example of interpolate colors, this one adds transparency, see https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/color-mix#adding_transparency  */
  --color-muted-foreground: color-mix(
    in oklch,
    var(--color-base-content) 60%,
    transparent
  );
  
  --color-destructive: var(--color-error);
  --color-destructive-foreground: var(--color-error-content);

  /** chart values taken from shadcn/ui template */
  --color-chart-1: hsl(12 76% 61%);
  --color-chart-2: hsl(173 58% 39%);
  --color-chart-3: hsl(197 37% 24%);
  --color-chart-4: hsl(43 74% 66%);
  --color-chart-5: hsl(27 87% 67%);

  --color-sidebar: color-mix(in oklch, var(--color-base-200) 20%, transparent);
  --color-sidebar-foreground: var(--color-base-content);
  --color-sidebar-primary: var(--color-primary);
  --color-sidebar-primary-foreground: var(--color-primary-content);
  --color-sidebar-accent: var(--color-accent);
  --color-sidebar-accent-foreground: var(--color-accent-content);
  --color-sidebar-border: var(--color-border);
  --color-sidebar-ring: var(--color-ring);
}

/** border color, see https://tailwindcss.com/docs/v4-beta#default-border-color-change */
@layer base {
  *,
  ::after,
  ::before,
  ::backdrop,
  ::file-selector-button {
    border-color: var(--color-border, currentColor);
  }
}
```

I haven't looked into borderRadius, keyframes and animation yet as I am good with the radius and I am not using the Accordion component, here are some tips
- borderRaidus might be set through [`--radius-*`](https://tailwindcss.com/docs/v4-beta#namespace-reference)
- [Configuring animations and keyframes](https://tailwindcss.com/docs/v4-beta#configuring-animations-and-keyframes)
