### DISCUSSION TITLE
Is it possible to use hsla with themes variables

### DISCUSSION THREAD

**Discussion by Yrobot** [saadeghi/daisyui#2170] [Q&A] [answered]
```css
.text-tip {
    color: hsla(var(--in), 0.5);
}
```
is not working, because the css varibale `--in` is `212 100% 48%`, 

when i change the variable `--in` to  `212, 100%, 48%`, the color change works.
