### DISCUSSION TITLE
Can you consider working with the `corePlugins.preflight` option to be turned off?

### DISCUSSION THREAD

**Discussion by u3u** [saadeghi/daisyui#2260] [Ideas / feature requests]
Due to our older project, the default `preflight` may have an impact on the overall website style, so we have to disable it.

Currently, I need to reset some basic styles for the `daisyui` components myself; otherwise, the component's style will be completely destroyed.

```css
[class*='daisy-'] {
  box-sizing: border-box;

  *,
  ::before,
  ::after {
    box-sizing: inherit;
  }
}

.daisy-input,
.daisy-textarea,
.daisy-select {
  transition: 0.3s, height 0s;
  outline: none !important;

  &::placeholder {
    color: #969696;
  }
}

.daisy-btn,
.daisy-input,
.daisy-textarea,
.daisy-select {
  border-style: solid;

  *,
  ::before,
  ::after {
    border-style: inherit;
    box-sizing: inherit;
  }
}

.daisy-tooltip {
  ::before {
    border-style: none;
  }

  ::after {
    border-style: solid;
  }
}
```
