### DISCUSSION TITLE
React-Select Dropdown Inside DaisyUI Collapse Component Not Expanding Parent

### DISCUSSION THREAD

**Discussion by IcedMonk** [saadeghi/daisyui#2273] [Q&A] [answered]
Hello,

I am using the DaisyUI library's collapse component and am facing an issue when embedding a react-select dropdown inside the collapse content.

The problem is that when the react-select dropdown is opened, the options list doesn't expand the parent collapse component. I've tried several CSS fixes, including adjusting the z-index and overflow properties, but none have resolved the issue.

Here's a code snippet illustrating the problem:

```jsx
<div className="collapse collapse-plus border border-base-300 my-3 font-bold">
  <input type="checkbox" className="peer" />
  <div className="collapse-title bg-gray-300 text-sm font-bold peer-checked:bg-gray-100 peer-checked:text-gray-900">
    Group By
  </div>
  <div className="collapse-content">
    <div>
      <label htmlFor="groupby" className="block text-gray-700 text-sm font-bold mb-2 mt-4">
        Group By
      </label>
      <Select
        name="groupby"
        styles={customStyles}
        isMulti
        options={fields}
        onChange={(selectedOptions) => setFieldValue("groupby", selectedOptions)}
        value={values.groupby}
      />
      <ErrorMessage name="groupby" component="div" className="text-red-500 text-xs" />
    </div>
  </div>
</div>
```
The collapse component's CSS is as follows:
```css
.collapse {
  position: relative;
  display: grid;
  overflow: hidden;
  grid-template-rows: auto 0fr;
  transition: grid-template-rows 0.2s;
}
/* ... rest of the collapse CSS ... */
```
I've attempted to override the CSS for the specific collapse component, but it didn't work:
```css
.group-by-collapse .collapse-content {
  overflow: visible !important;
  position: relative;
}

.group-by-collapse .collapse-content > div {
  position: absolute !important;
  z-index: 999;
}
```

I would like the collapse content to expand when the react-select options are opened, allowing the user to view and interact with the options. Is there a recommended approach for achieving this behavior with the DaisyUI collapse component and react-select?

Thank you!

**Comment by IcedMonk** [comment]
Hey buddy @saadeghi , can you please let me know if it is possible, or no?
Actually, my project is on halt due to this issue.

**Comment by IcedMonk** [comment, marked as answer]
Hello again,

I've found a solution to the issue with the DaisyUI collapse component and react-select dropdown, and I wanted to share it here in case it helps anyone else in the future.

The problem was caused by the `overflow: hidden` property in the `.collapse` class, which was clipping the react-select options list when it extended beyond the boundaries of the collapse component.

Here's the solution:

### 1. Add a Custom Class to the Specific Collapse Section:
   I added a custom class (e.g., `custom-collapse`) to the specific collapse section containing the react-select dropdown.

   ```jsx
   <div className="custom-collapse collapse collapse-plus border border-base-300 my-3 font-bold">
     {/* ... */}
   </div>
```
### 2. Override the Overflow Property in the CSS File:
 I added the following CSS rule to my project's CSS file (e.g., **index.css**).
```css
.custom-collapse.collapse {
  overflow: visible; /* or 'unset' */
}
```

This solution changed the overflow behavior only for the specific collapse section containing the react-select dropdown, leaving other instances of the collapse component unaffected.

Thank you, I hope this solution is helpful to others facing a similar issue!
