### DISCUSSION TITLE
Close tooltip after few second

### DISCUSSION THREAD

**Discussion by vaibhavsharma-saaslabs** [saadeghi/daisyui#2281] [Q&A] [answered]
how to close tooltip after few seconds?

**Comment by saadeghi** [comment, marked as answer]
I wouldn't recommend that. Tooltips should be visible based on user's interaction, not a timer.  
However, if you really want to do that, you can add some CSS like this:  
https://play.tailwindcss.com/6fiN783izN?file=css
```css
.tooltip:hover:before,
.tooltip:hover:after {
  opacity: 0;
  animation: 2s fade-tooltip;
}

@keyframes fade-tooltip {
  0%, 90% {
    opacity: 1;
  }
  100% {
    opacity: 0;
  }
}
```
