### DISCUSSION TITLE
How to remove table Header Radius on V2.52

### DISCUSSION THREAD

**Discussion by Mashiane** [saadeghi/daisyui#2347] [Q&A] [answered]
Hi

Disclaimer: I am yet to upgrade to V3.

![image](https://github.com/saadeghi/daisyui/assets/5799306/3bb77de1-964c-4eed-b05e-b7590bca8720)

I am managing to apply most of what I need on the table. Im just stuck with the radius on the table on the header and footer. How can I have it removed? It seems its added automatically, I could be wrong.

Thank you so much.

**Comment by saadeghi** [comment, marked as answer]
This is not an issue on version 3.  
For v2, you can add a CSS like this to remove that radius:  
```css
.table *:first-child :where(th, td):first-child {
    border-top-left-radius: 0;
}
.table *:first-child :where(th, td):last-child {
    border-top-right-radius: 0;
}
```

https://play.tailwindcss.com/0b1oHAZDpb?file=css
