### DISCUSSION TITLE
Use :focus-within and :focus on input component

### DISCUSSION THREAD

**Discussion by tronikelis** [saadeghi/daisyui#2350] [Ideas / feature requests]
Heya, 

I am building an autocomplete input component that can select multiple items, which are shown in the input itself:

![image](https://github.com/saadeghi/daisyui/assets/56039679/f1a5a067-f0ec-4bf1-b4c8-bd5ced337f77)

So I am using `input` classes not on the inner input element but on the outer div element like this:

```html
<div class="flex flex-row input ....">
    <input />
</div>
```

But I lose focus states because divs are not focusable, I tried setting a tab index which does not solve the problem.

Now adding another css selector like this:

```css
.input:focus-within {
    outline-style: solid;
    outline-width: 2px;
    outline-offset: 2px;
    outline-color: hsl(var(--bc) / 0.2);
}
```

Solves the problem, but I don't like the idea of copy pasting this for all colors and modes.

So would it be possible to just apply the focus styles to the `:focus-within` selector as well?
