### DISCUSSION TITLE
prefers-reduced-motion

### DISCUSSION THREAD

**Discussion by nandi95** [saadeghi/daisyui#2367] [Ideas / feature requests]
[Docs](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)
I can see a couple components where this could be added to respect the user's browser preference:
Button,
Tooltip
Collapse/Accordion
Swap
Radio
Modal
Checkbox
Dropdown
Menu(statuses)

**Comment by saadeghi** [comment]
I think `prefers-reduced-motion` is for reducing the animated parts, not removing them. It's useful when there are a big moving parts or long animations and they may be annoying to the users.  
Micro transitions like a button hover style or checkbox, etc... are so small and fast that wont be annoying to the users.

**Reply by danawoodman** [reply]
One counterpoint, I'm writing some screenshot diffing tests with Puppeteer and Daisy's animations are causing subtle failures because of motion. An ability to remove any animation for cases like this would be super helpful (as now I have to simulate a delay)

**Reply by saadeghi** [reply]
Can you tell me more about the test which is failing?

**Reply by danawoodman** [reply]
Current workaround that seems to work is to set this in my CSS file:

```css
@media (prefers-reduced-motion: reduce) {
	* {
		animation-duration: 0.001ms !important;
		transition-duration: 0.001ms !important;
		animation-iteration-count: 1 !important;
		background-image: none !important;
	}
}
```

Then I set prefers-reduced-motion with Puppeteer (would be same with Playwright etc):

```js
await page.emulateMediaFeatures([
  { name: "prefers-reduced-motion", value: "reduce" },
]);
```
