### DISCUSSION TITLE
Position the submenu on menu component

### DISCUSSION THREAD

**Discussion by guillegette** [saadeghi/daisyui#2414] [Q&A] [answered]
Hi there,

Any ideas how I can make the submenu in the menu component https://daisyui.com/components/menu/ to open on top of the menu, rather than always the bottom? 

I am using the menu component in the footer of my application so I need the submenu to open above the menu. 

My current workaround is to simply use a dropdown component as a menu item so I can control how it opens. But would love to use the native markup.

**Comment by saadeghi** [comment, marked as answer]
You can customize it like this:  
https://play.tailwindcss.com/86vBrYeo0X?file=css
```css
/* push the submenu to top */
.menu-horizontal > li > details > ul{
  top: auto;
  bottom: 3rem;
}

/* rotate the arrow */
.menu :where(li > details > summary):after {
  transform: rotate(225deg);
  margin-top: 0;
}
.menu :where(li > details[open] > summary):after {
  transform: rotate(45deg);
  margin-top: -.5rem;
}
```
