### DISCUSSION TITLE
color-mix not support under chrome 111, can set fallback?

### DISCUSSION THREAD

**Discussion by wenzhili** [saadeghi/daisyui#2576] [Ideas / feature requests]
color-mix not support under chrome 111, but some computer is installed windows 7 , can't install high chrome, can set fallback?

**Comment by sveltarne** [comment]
I completely agree, theres a good amount of devices that cant get 2023 browser versions, like my old chromebook. It would be really useful if you could set the fallback theme, since every non-daisyUI website works just fine on my chromebook.

**Comment by saadeghi** [comment]
Windows 7 came 14 years ago my friend. Upgrade to a Linux or something else 😁  

`color-mix()` is supported in Chrome 111+, FireFox 113+ and Safari 16.2+  
`oklch()` colors are supported in Chrome 111+, Firefox 113+ and Safari 15.4+

daisyUI 4 uses `oklch()` colors for all themes but it shows fallback colors of default (`light`, `dark`) themes for older browsers.  
Here you can see the CSS variables for fallback colors: https://github.com/saadeghi/daisyui/blob/master/src/base/colors.css

Older browsers show the default (light/dark) themes and it doesn't break the website.  
We can't provide fallback for all themes because of CSS size, but you can manually add fallback hex colors for the themes you want.

daisyUI is using `color-mix()` for `btn-active` styles (it's not being used everywhere) and I think the only think the usage of `color-mix()` is breaking for old browsers is `btn btn-active` (will be fixed today in daisyUI `4.4.8`)  
Other than that, the website is still useable (using the fallback colors)

Let me know if you have a question.

**Reply by sveltarne** [reply]
but i cant set fallback hex colors without making my own fork/build of daisyUI?

**Reply by saadeghi** [reply]
@sveltarne You can. See this example:  
https://play.tailwindcss.com/3HBrQnuBVw?file=css  
You can set fallback colors for the light/dark theme like the example, or you can set them for other themes or your custom theme.

Let me know if you have a question.

**Reply by ozdemirburak** [reply]
Thanks, @saadeghi for the workaround. 

If `oklch` is not supported, changing the `data-theme` attribute seems to have no effect. So, you need to implement it yourself again, right?

I think this solves it:

```css
@supports not (color: oklch(0 0 0)) {
    :root, [data-theme=dracula] {
         --fallback-p: #ff79c6;
         ...
         --fallback-erc: #160202;
    }
    [data-theme=fantasy] {
         --fallback-p: #6d0076;
         ...
         --fallback-erc: #000;
    }
}
```

However, I believe that for `.select-bordered`, `.input-bordered`, etc., you still need to explicitly define colors.
