### DISCUSSION TITLE
Replace the `select` arrow with the Tailwind Forms chevron

### DISCUSSION THREAD

**Discussion by Teraskull** [saadeghi/daisyui#2954] [Ideas / feature requests]
Purely for visual appeal, it looks cleaner than the default triangle.

```css
.form-select {
	background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' fill='none' viewBox='0 0 20 20'%3e%3cpath stroke='%236b7280' stroke-linecap='round' stroke-linejoin='round' stroke-width='1.5' d='M6 8l4 4 4-4'/%3e%3c/svg%3e");
}
```
Before:

![image](https://github.com/saadeghi/daisyui/assets/24798198/db3fa887-7df0-4a43-9df3-6eef3800202c)

After:

![image](https://github.com/saadeghi/daisyui/assets/24798198/8cc30c33-0b3e-4d24-b164-62b0dec13802)
