### DISCUSSION TITLE
How to override default step-vertical style

### DISCUSSION THREAD

**Discussion by ghost** [saadeghi/daisyui#3072] [Q&A]
```css
.steps-vertical .step {
  gap: 0.5rem/* 8px */;
  grid-template-columns: 40px 1fr;
  grid-template-rows: auto;
  min-height: 4rem/* 64px */;
  justify-items: start;
}
```
I want to change the `min-height: 4rem` to something smaller to fit landscape mobile devices. 
Could you help show me how to do that in this div below?
```html
<ul
	class="steps steps-vertical sticky top-16 z-10 h-[calc(100dvh-4rem)] min-w-min xl:hidden"
>
</ul>
```
