### DISCUSSION TITLE
How to use themes with CDN

### DISCUSSION THREAD

**Discussion by henriqueleite42** [saadeghi/daisyui#3133] [Q&A] [answered]
In the docs, the only way to customize DaisyUi is using the `tailwind.config.js`, but it seems to not work when importing it from a CDN. Is there any way to add themes to it?

When I try to add themes manually by creating a css file with all the variables, like the one below (`my-custom-themes.css`):
```css
:root {
	color-scheme: light;
	--inc: 0% 0 0;
	--suc: 0% 0 0;
	--wac: 0% 0 0;
	--erc: 0% 0 0;
	--rounded-box: 1rem;
	--rounded-btn: 0.5rem;
	--rounded-badge: 1.9rem;
	--animation-btn: 0.25s;
	--animation-input: .2s;
	--btn-focus-scale: 0.95;
	--border-btn: 1px;
	--tab-border: 1px;
	--tab-radius: 0.5rem;

	--p: 0 48% 100%;
	--pf: 0 36% 71%;
	--pc: 255 100% 100%;
	--s: 52 78% 35%;
	--sf: 40 65% 27%;
	--sc: 255 100% 100%;
	--a: 249 45% 9%;
	--af: 234 35% 5%;
	--ac: 255 100% 100%;
	--n: 28 11% 12%;
	--nf: 0 0% 0%;
	--nc: 255 100% 100%;
	--b1: 255 100% 100%;
	--b2: 245 96% 97%;
	--b3: 209 82% 84%;
	--bc: 0 0% 0%;
	--in: 59 51% 96%;
	--su: 34 77% 37%;
	--wa: 251 75% 14%;
	--er: 239 27% 27%;
	--rounded-box: 0.5rem;
	--rounded-btn: 0.25rem;
	--rounded-badge: 1rem;
	--animation-btn: .2s;
	--animation-input: .2s;
	--btn-text-case: capitalize;
	--navbar-padding: 1rem;
	--border-btn: 1px;
}
```

It seems to ignore the values and everything becomes black and white.

When I use the `tailwing.config.css`, it also ignores the config and at best uses the default light theme.

My `<head>` content:
```html
	<link rel="stylesheet" href="/static/css/days-ui.min.css" type="text/css"/>
	<link rel="stylesheet" href="/static/css/my-custom-themes.css" type="text/css"/>
	<script src="/static/js/tailwind.min.js"></script>
	<script src="/static/js/tailwind.config.js"></script>
```
Instead of importing from the CDN I'm downloading the file and serving it on my own server, but the content is the same as the one in the CDN ([https://cdn.jsdelivr.net/npm/daisyui@4.12.10/dist/full.min.css](https://cdn.jsdelivr.net/npm/daisyui@4.12.10/dist/full.min.css) and [https://cdn.tailwindcss.com](https://cdn.tailwindcss.com)).

I also noticed that the css changes when I add the `my-custom-themes.css`.
Before:
![image](https://github.com/user-attachments/assets/5ab41c00-76a4-4931-8bc6-91bccb99818c)
After:
![image](https://github.com/user-attachments/assets/e6458f27-a9e3-4920-8fa1-a3f47efb43d0)
This is because the value of the `--p` variable is not right, which pattern do you guys use on the color values? Is it HSL?

Is it mandatory to use a build step to configure it? DaisyUI doesn't work properly with CDNs?

**Comment by henriqueleite42** [comment]
I was able to fix it, the problem was the format of the colors that I was using.

I created a theme using [this amazing website](https://themes.ionevolve.com), but unfortunately it only exports the themes to JSON config. To be able to use it as CSS I had to convert the colors to the format that DaisyUI uses, what took a few tries (first HSL, them an entire journey to oklch).

After a long time, I finally was able to get hex to oklch, and the theme worked.

**Reply by aalaap** [reply]
That's great! Can you post an example here? Even I'm struggling with this.

**Reply by saadeghi** [reply, marked as answer]
@aalaap These are the CSS variables:  
https://unpkg.com/browse/daisyui@4.12.10/dist/themes.css

For example `--p: 49.12% 0.3096 275.75;` is `primary` color ([docs](https://daisyui.com/docs/colors/)) and the value `49.12% 0.3096 275.75` is OKLCH `lightness` `chroma` `hue`.

You can play with them or convert them in this website: https://oklch.com/

To add a new custom theme using CDN (if you don't have a Tailwind node setup to generate the CSS file) you can add a CSS file to your project with this:
```css
[data-theme=mytheme] {
    color-scheme: light;
    --in: 72.06% 0.191 231.6;
    --su: 64.8% 0.150 160;
    --wa: 84.71% 0.199 83.87;
    --er: 71.76% 0.221 22.18;
    --pc: 89.824% 0.06192 275.75;
    --ac: 15.352% 0.0368 183.61;
    --inc: 0% 0 0;
    --suc: 0% 0 0;
    --wac: 0% 0 0;
    --erc: 0% 0 0;
    --rounded-box: 1rem;
    --rounded-btn: 0.5rem;
    --rounded-badge: 1.9rem;
    --animation-btn: 0.25s;
    --animation-input: .2s;
    --btn-focus-scale: 0.95;
    --border-btn: 1px;
    --tab-border: 1px;
    --tab-radius: 0.5rem;
    --p: 49.12% 0.3096 275.75;
    --s: 69.71% 0.329 342.55;
    --sc: 98.71% 0.0106 342.55;
    --a: 76.76% 0.184 183.61;
    --n: 32.1785% 0.02476 255.701624;
    --nc: 89.4994% 0.011585 252.096176;
    --b1: 100% 0 0;
    --b2: 96.1151% 0 0;
    --b3: 92.4169% 0.00108 197.137559;
    --bc: 27.8078% 0.029596 256.847952
}
```
and customize the colors. then you can use your theme like `<html data-theme="mytheme">`

Let me know if you have a question.
