### DISCUSSION TITLE
Re. Modal transparency in nuxt works fine in tailwind playground

### DISCUSSION THREAD

**Discussion by DenjixPochita** [saadeghi/daisyui#3290] [Q&A]
Hi, I am bit confused is it Nuxtjs bug or Daisy UI because it works fine in tailwind playground.
![image](https://github.com/user-attachments/assets/ffe89597-f573-46c4-8563-1b5a9fe46839)

Code:
```
<template>
  <div>
    <div class="hero bg-base-200 min-h-screen">
      <div class="hero-content text-center">
        <div class="max-w-md">
          <h1 class="text-5xl font-bold">Test</h1>
          <p class="py-6">Hello</p>
          <!-- Open the modal using ID.showModal() method -->
          <button class="btn" onclick="test.showModal()">Click</button>
        </div>
      </div>
    </div>
    <dialog id="test" class="modal modal-bottom sm:modal-middle bg-base-400">
      <div class="modal-box">
        <h3 class="text-lg font-bold">Select</h3>
        <p class="py-4">Press ESC key or click the button below to close</p>
        <div class="modal-action">
          <form method="dialog">
            <!-- if there is a button in form, it will close the modal -->
            <button class="btn">Done</button>
          </form>
        </div>
      </div>
    </dialog>
  </div>
</template>
```

Url: https://stackblitz.com/edit/nuxt-starter-yzb4hs?file=app.vue

Thanks!

**Comment by unrevised6419** [comment]
The daisyUI config is set to no themes. That's why that `--b1` does not exist.

```css
.modal-box {
  background-color: var(--fallback-b1,oklch(var(--b1)/var(--tw-bg-opacity)));
                                               /* ^ var not set because there are no themes */
}
```

![image](https://github.com/user-attachments/assets/ea631e0a-65df-4d86-9c2b-9fcb6a1ed602)

Set themes to false, which will include only light and dark themes.

<img width="510" alt="image" src="https://github.com/user-attachments/assets/be76d8a3-da3c-437f-93da-abec3cbfb7ee">
