### DISCUSSION TITLE
v5: How to use @apply with daisy classes

### DISCUSSION THREAD

**Discussion by amir20** [saadeghi/daisyui#3361] [Q&A] [answered]
Thank you for the amazing library. I am trying to upgrade to v5. Many things break but the first one I noticed is this one: 

```css
@utility active-primary {
  --n: var(--p);
  --nc: var(--pc);
  @apply active;
}
```

According to docs, `active` has been renamed to `menu-active`. However, that still breaks: 

```css
@utility active-primary {
  --n: var(--p);
  --nc: var(--pc);
  @apply menu-active;
}
```

```
[vite:css] [postcss] Cannot apply unknown utility class: menu-active
file: /Users/amirraminfar/Workspace/dozzle/assets/main.css:undefined:NaN
```

At the top, I have: 

```css
@import "tailwindcss";
@plugin "daisyui";
@config '../tailwind.config.ts';
```

I assume I need to some how to import so that is visible to tailwind.
