### DISCUSSION TITLE
DaisyUI prefers-color-scheme Not Working in Chrome

### DISCUSSION THREAD

**Discussion by frst-mg** [saadeghi/daisyui#3516] [Q&A]
Hi everyone,

I'm having an issue with DaisyUI where the prefers-color-scheme setting works correctly in Brave and Firefox but not in Chrome. 

In Chrome, it only applies the dark mode theme regardless of the browser's prefers-color-scheme setting. Has anyone else encountered this issue or have any suggestions on how to fix it?

```css
@import 'tailwindcss';
@plugin "daisyui";
```

Using :
"tailwindcss": "^4.0.7"
"daisyui": "^5.0.0-beta.8",

Thanks in advance for your help!

**Comment by saadeghi** [comment]
Can you try with incognito mode?  
Do you have any Chrome extension that may effect the styles?

**Reply by frst-mg** [reply]
I tried incognito it dosen't work, i have those extensions:
![Screenshot 2025-02-19 at 13 41 33](https://github.com/user-attachments/assets/381309d4-578c-4615-93eb-43c2a0c7d4bd)
Disabled ColorZilla since next js throws errors because of it.

**Comment by saadeghi** [comment]
It's hard to guess without seeing the project.  
Do you have `data-theme` in the HTML setting a specific theme?  
Can you try changing Chromes prefers-color-scheme from devtools?  

https://github.com/user-attachments/assets/b9130898-56ad-4cfd-8c7b-ea25a69baee0

**Reply by frst-mg** [reply]
I dont have a data-theme in the html i only have this in css:
```css
@import 'tailwindcss';
@plugin "daisyui";

@plugin "daisyui/theme" {
  name: 'light';
  default: true;
  --color-primary: #2a5099;
}

@plugin "daisyui/theme" {
  name: 'dark';
  prefersdark: true;
  --color-primary: #2a5099;
}

input[type='text'] {
  @apply focus:outline-none;
}

@theme {
  --breakpoint-xs: 30rem;
}
```

I can toggle like you show in the video.
