### DISCUSSION TITLE
Make tabs take full height of the parent (when needed)

### DISCUSSION THREAD

**Discussion by cretucosmin3** [saadeghi/daisyui#3707] [Ideas / feature requests]
There are many cases where you'd need tabs to take full height of the parent, for example if you're using grids in your app / site.

https://play.tailwindcss.com/7hDOxgOn8A

![image](https://github.com/user-attachments/assets/222a814a-dada-46b5-948e-59f32b2d6178)

The code can probably be merged / adapted into the code of the tabs.

``` CSS
.tabs {
  &.tabs-h-full {
    height: 100%;

    --tab-height-multiplier: 10;

    > .tab-content {
      height: calc(100% - calc(var(--size-field, 0.25rem) * var(--tab-height-multiplier)));
    }

    &.tabs-xs {
      --tab-height-multiplier: 6;
    }

    &.tabs-sm {
      --tab-height-multiplier: 8;
    }

    &.tabs-md {
      --tab-height-multiplier: 10;
    }

    &.tabs-lg {
      --tab-height-multiplier: 12;
    }

    &.tabs-xl {
      --tab-height-multiplier: 14;
    }
  }
}
```
