### DISCUSSION TITLE
Custom theme with Tailwind Standalone CLI

### DISCUSSION THREAD

**Discussion by Bhacaz** [saadeghi/daisyui#3717] [Q&A] [answered]
Hi, I had a hard time figuring out how to use a [custom theme](https://daisyui.com/docs/themes/#how-to-add-a-new-custom-theme) when using only the Tailwind Standalone CLI. I followed the Rails + Bundle File [instructions](https://daisyui.com/docs/install/rails/#3-add-daisyui), which worked great.

All the theme references in the documentation use `@plugin "daisyui/theme" { ... }`, but this doesn't work when using @plugin "./daisyui.js";.

I finally got it working by following the same format used in CDN theme files, such as [daisyui@5/theme/light.css](https://cdn.jsdelivr.net/npm/daisyui@5/theme/light.css):

```css
@import "tailwindcss";
@plugin "./daisyui.js";

:root, :root:has(input.theme-controller[value=light]:checked), [data-theme="mytheme"] {
  name: "mytheme";
  default: true;
  prefersdark: true;
  color-scheme: "dark";
  --color-base-100: oklch(12% 0.042 264.695);
  ...
}
```
And it works!

So, here’s my question/comment:

- Is there a better way to use a custom theme when using `@plugin "./daisyui.js"`?
- Is this documented somewhere? I couldn’t find it, but if not, it would be a great addition.

Thanks!
