### DISCUSSION TITLE
Update to V5 results in different colors

### DISCUSSION THREAD

**Discussion by jav-ed** [saadeghi/daisyui#3744] [Q&A] [answered]
Hi, I have a project that works just fine with astroj and daisyUI:

```json
"devDependencies": {
    "@tailwindcss/typography": "^0.5.14",
    "autoprefixer": "^10.4.20",
    "daisyui": "^3.9.4",
    "postcss-nesting": "^12.1.5",
    "postcss-preset-env": "^9.6.0",
    "rollup-plugin-visualizer": "^5.12.0"
  },
```

Now, I updated tailwindcss ( "@tailwindcss/vite": "^4.0.17"), astrojs ("astro": "^5.5.6") and daisyUI ("daisyui": "^5.0.9")

```json
  "devDependencies": {
    "@tailwindcss/typography": "^0.5.16",
    "autoprefixer": "^10.4.21",
    "daisyui": "^5.0.9",
    "npm": "^11.2.0",
    "postcss-nesting": "^13.0.1",
    "postcss-preset-env": "^10.1.5",
    "rollup-plugin-visualizer": "^5.14.0"
  },
```
Previously, I used the following snippet for a custom in theme (tailwind.config.cjs)

```cjs
    daisyui:{
      // themes: false, // true: all themes | false: only light + dark | array: specific themes like this ["light", "dark", "cupcake"]

      /* ------------------------------- themes ------------------------------- */
      themes: [
        {

          /* ----------------------- daisy default theme ---------------------- */
          theme_Jav_0: {
            ...require("daisyui/src/theming/themes")["[data-theme=dark]"],

            primary: colors.green[500],
            secondary: colors.sky[500],
            accent: colors.violet[500],
            "base-100": "#000",
            "base-200": "#000",

            // font color
            "base-content": "#ffffff",
            // "--rounded-btn": "1.9rem",

            "fontFamily":"platypi",

          },
          theme_Jav_1: {
            ...require("daisyui/src/theming/themes")["[data-theme=dark]"],

            primary: colors.green[500],
            secondary: colors.sky[500],
            accent: colors.violet[500],
            // "--rounded-btn": "1.9rem",

          },
....
...

```
This snippet would result in the 4 colors depicted in the image (initial)
![inital](https://github.com/user-attachments/assets/4bb51be0-4212-44bf-bf68-a3e77d6c0bef)

With the current update, I get the colors depicted in the image (after)
![after](https://github.com/user-attachments/assets/92d3321b-10e6-4d82-9f1c-df6d970ec676)

The theme switcher shows 4 colors, and the fourth color is not really visible. Previously, I did not need to define all colors, just the few mentioned above in the tailwind.config.cjs. I tried the same thing for the new version in a separate css. Depending on having selected the theme or not, different colors would be shown.  Because both themes are just modifications of the dark theme, I tried the following:

```css
/* ------------------------------- theme_Jav_0 ------------------------------ */
@plugin "daisyui/theme" {
    name: "theme_Jav_0";
    default: false; /* not default light theme */
    prefersdark: true; /* default dark theme */
    color-scheme: "dark";

    --color-base-100: #000;
    --color-base-200: #000;
    --color-base-300: oklch(21.15% 0.012 254.09);
    --color-base-content: #ffffff;
    
    --color-primary: var(--color-green-500);
    --color-primary-content: oklch(96% 0.018 272.314);

    --color-secondary: var(--color-sky-500);
    --color-secondary-content: oklch(94% 0.028 342.258);

    --color-accent: var(--color-violet-500);
    --color-accent-content: oklch(38% 0.063 188.416);
    --color-neutral: oklch(14% 0.005 285.823);
    --color-neutral-content: oklch(92% 0.004 286.32);
    --color-info: oklch(74% 0.16 232.661);
    --color-info-content: oklch(29% 0.066 243.157);
    --color-success: oklch(76% 0.177 163.223);
    --color-success-content: oklch(37% 0.077 168.94);
    --color-warning: oklch(82% 0.189 84.429);
    --color-warning-content: oklch(41% 0.112 45.904);
    --color-error: oklch(71% 0.194 13.428);
    --color-error-content: oklch(27% 0.105 12.094);
    --radius-selector: 0.5rem;
    --radius-field: 0.25rem;
    --radius-box: 0.5rem;
    --size-selector: 0.25rem;
    --size-field: 0.25rem;
    --border: 1px;
    --depth: 1;
    --noise: 0; 
}

/* ------------------------------- theme_Jav_1 ------------------------------ */
@plugin "daisyui/theme" {
    name: "theme_Jav_1";
    default: false; /* NOT default light theme */
    prefersdark: false; /* NOT default dark theme */
    color-scheme: "dark";

        
    --color-base-100: oklch(25.33% 0.016 252.42);
    --color-base-200: oklch(23.26% 0.014 253.1);
    --color-base-300: oklch(21.15% 0.012 254.09);

    --color-base-content: oklch(97.807% 0.029 256.847);
    --color-primary: var(--color-green-500);
    --color-primary-content: oklch(96% 0.018 272.314);

    --color-secondary: var(--color-sky-500);
    --color-secondary-content: oklch(94% 0.028 342.258);

    --color-accent: var(--color-violet-500);
    --color-accent-content: oklch(38% 0.063 188.416);
    --color-neutral: oklch(14% 0.005 285.823);
    --color-neutral-content: oklch(92% 0.004 286.32);
    --color-info: oklch(74% 0.16 232.661);
    --color-info-content: oklch(29% 0.066 243.157);
    --color-success: oklch(76% 0.177 163.223);
    --color-success-content: oklch(37% 0.077 168.94);
    --color-warning: oklch(82% 0.189 84.429);
    --color-warning-content: oklch(41% 0.112 45.904);
    --color-error: oklch(71% 0.194 13.428);
    --color-error-content: oklch(27% 0.105 12.094);
    --radius-selector: 0.5rem;
    --radius-field: 0.25rem;
    --radius-box: 0.5rem;
    --size-selector: 0.25rem;
    --size-field: 0.25rem;
    --border: 1px;
    --depth: 1;
    --noise: 0; 

}
```
With this attempt, you get the 4 colors shown in the image above (after). I looked at [https://github.com/saadeghi/daisyui/blob/v4/src/theming/themes.js](https://github.com/saadeghi/daisyui/blob/v4/src/theming/themes.js) and saw the definition of the dark theme:

```js
  dark: {
    "color-scheme": "dark",
    "primary": "oklch(65.69% 0.196 275.75)",
    "secondary": "oklch(74.8% 0.26 342.55)",
    "accent": "oklch(74.51% 0.167 183.61)",
    "neutral": "#2a323c",
    "neutral-content": "#A6ADBB",
    "base-100": "#1d232a",
    "base-200": "#191e24",
    "base-300": "#15191e",
    "base-content": "#A6ADBB",
  },
```

You can see that not all colors are defined in DaisyUI version 3. From what I remember, DaisyUI used to compute the other remaining colors as needed?

---

With this background, how can I get the colors of DaisyUI version 3 back?

**Comment by saadeghi** [comment, marked as answer]
Some built-in theme colors had adjustments last year from v3 to v4 and last month from v4 to v5.  
So as you were extending built-in themes, those colors are slightly different comparing to v3.  

Here you can find v3 colors:  
https://app.unpkg.com/daisyui@3.9.4/files/dist/themes.css  
You can make a new custom daisyUI 5 theme and use the old colors as `hsl()`. For example `--color-primary: hsl(259 94% 51%);`  


Let me know if you have any questions.

**Comment by jav-ed** [comment]
Thanks for your quick reply.

Maybe I am misunderstanding something. I was thinking that  ` prefersdark: true; ` would set the default theme for the dark mode. However, with the following, the selection of the light theme will be neglected, and the dark theme is chosen instead.

```css
@plugin "daisyui/theme" {
    name: "light";
    default: true;
    prefersdark: false;
    color-scheme: "light";
}

/* ------------------------------- theme_Jav_0 ------------------------------ */
@plugin "daisyui/theme" {
    name: "theme_Jav_0";
    default: false; /* not default light theme */
    prefersdark: true; /* default dark theme */
    color-scheme: "dark";

    --color-base-100: #000;
    --color-base-200: #000;
    --color-base-300: oklch(21.15% 0.012 254.09);
    --color-base-content: #ffffff;
    
    --color-primary: var(--color-green-500);
    --color-primary-content: oklch(96% 0.018 272.314);

    --color-secondary: var(--color-sky-500);
    --color-secondary-content: oklch(94% 0.028 342.258);

    --color-accent: var(--color-violet-500);
    --color-accent-content: oklch(38% 0.063 188.416);
    --color-neutral: oklch(14% 0.005 285.823);
    --color-neutral-content: oklch(92% 0.004 286.32);
    --color-info: oklch(74% 0.16 232.661);
    --color-info-content: oklch(29% 0.066 243.157);
    --color-success: oklch(76% 0.177 163.223);
    --color-success-content: oklch(37% 0.077 168.94);
    --color-warning: oklch(82% 0.189 84.429);
    --color-warning-content: oklch(41% 0.112 45.904);
    --color-error: oklch(71% 0.194 13.428);
    --color-error-content: oklch(27% 0.105 12.094);
    --radius-selector: 0.5rem;
    --radius-field: 0.25rem;
    --radius-box: 0.5rem;
    --size-selector: 0.25rem;
    --size-field: 0.25rem;
    --border: 1px;
    --depth: 1;
    --noise: 0; 
}
```

![dark_neglected](https://github.com/user-attachments/assets/9776d759-7ab4-4ea8-ba88-713fef1701e8)
