### DISCUSSION TITLE
Semicolon on @plugin produces a syntax highlight problem

### DISCUSSION THREAD

**Discussion by LEstradioto** [saadeghi/daisyui#3832] [Q&A] [answered]
Following this: https://github.com/tailwindlabs/tailwindcss-intellisense/issues/1340

There is an issue with the `@plugin` directive when used with a configuration block in Tailwind CSS v4. There seems to be confusion about whether a semicolon is required after closing a configuration block.

For example, with this code:

```css
@import "tailwindcss";
@plugin "@tailwindcss/typography";
@plugin "daisyui" {
  themes: false;
}; /* Does this semicolon belong here? */
```

When the semicolon is present after the block, syntax highlighting works correctly, but it triggers a compiler error: `Error: Unexpected semicolon`.
When removing the semicolon, the compiler works correctly, but syntax highlighting breaks for all code after the block.

This creates a difficult situation where developers must choose between correct highlighting or correct compilation. 

As noted in [issue #1340](https://github.com/tailwindlabs/tailwindcss-intellisense/issues/1340), this affects all formatters (dprint, biome, prettier) as they tend to remove the trailing semicolon, breaking the highlighting.

A workaround suggested by me is to add a commented semicolon:
```css
@plugin 'daisyui' {
  themes: all;
}

/*;*/
```

At Tailwind docs, it seems `@plugin` should be used to backward compatibility (maybe will be deprecated soon?)
So I guess Daisyui should solve this some other way, or is it possible to add that config differently?

My current use is like this:

```css
@plugin "daisyui" {
  themes: all;
}


@plugin "daisyui/theme" {
  name: "dark";
  --border: 2px;
  --depth: 1;
  --noise: 1;
};

@plugin "daisyui/theme" {
  name: "light";
  --border: 2px;
  --depth: 1;
  --noise: 1;
};
```
