### DISCUSSION TITLE
Changing `fallback + @supports` CSS output?

### DISCUSSION THREAD

**Discussion by YektaDev** [saadeghi/daisyui#3876] [Q&A]
Hi,

@saadeghi, first of all, thanks for the v5 efforts!

I'm not quite sure, but I wanted to know if this fallback generation behavior is being determined by daisyUI. For example:
```css
.navbar-menu-button-rect {
  @apply /*...*/ active:bg-primary/20! /*...*/;
}
```
Produces:
```css
.navbar-menu-button-rect:active {
  background-color: var(--color-primary) !important;
}
@supports (color: color-mix(in lab, red, red)) {
  .navbar-menu-button-rect:active {
    background-color: color-mix(in oklab, var(--color-primary) 20%, transparent) !important;
  }
}
```

If so, is there a way to configure the output for all theme colors to just generate the following, without the fallback?
```css
.navbar-menu-button-rect:active {
  background-color: color-mix(in oklab, var(--color-primary) 20%, transparent) !important;
}
```

I have found this pattern to be repeated throughout the CSS files, which nearly doubles the output size.
Thanks!
