### DISCUSSION TITLE
Add border removal functionality for labels

### DISCUSSION THREAD

**Discussion by daangnkim** [saadeghi/daisyui#3916] [Ideas / feature requests]
## Reason for Improvement

In cases where Korean won (KRW) input is required, borders may be unnecessary. Below is an example of inputting Korean currency (won).

![image](https://github.com/user-attachments/assets/16f15372-493a-4b1b-ad43-0111190422e0)

To remove these borders, we currently have to use `!border-none` as follow.

```html
<label className="input">
  <input type="text" placeholder="domain name" />
  <span className="label !border-none text-black">.com</span>
</label>
```

## Code Changes

The `!border-none` approach has the drawback of using `!important`, which ignores CSS specificity hierarchy and forcibly applies styles.

How about adding a `border-none` option as shown below?

```css
.label {
  @apply inline-flex items-center gap-1.5 whitespace-nowrap text-current/60;
  
  &:has(input) {
    @apply cursor-pointer;
  }
  
  &:is(.input > *, .select > *) {
    @apply flex h-[calc(100%-0.5rem)] items-center px-3 whitespace-nowrap;
    font-size: inherit;
    
    &:first-child:not(.border-none) {
      @apply -ms-3 me-3;
      border-inline-end: var(--border) solid color-mix(in oklab, currentColor 10%, #0000);
    }
    
    &:first-child.border-none {
      @apply -ms-3 me-3;
    }
    
    &:last-child:not(.border-none) {
      @apply ms-3 -me-3;
      border-inline-start: var(--border) solid color-mix(in oklab, currentColor 10%, #0000);
    }
    
    &:last-child.border-none {
      @apply ms-3 -me-3;
    }
  }
}
```

This provides a cleaner, more maintainable solution compared to using `!important` overrides.
