### DISCUSSION TITLE
Which component uses which colors?

### DISCUSSION THREAD

**Discussion by Robert-M-Muench** [saadeghi/daisyui#412] [General]
I'm trying to get some CI into a theme. 

However, I always have unwanted color side effects and I don't know which color each component uses by default. Is there a way to find that out? How about adding the default color to the docs?

Then, using colors explicitly doesn't have any effect on the component... wondering why this is the case.

It's pretty hard to get a theme adjusted/build-up where all the colors match. Is there a play.tailswind.css with a big page containing every component? So that I can see color change effects for all of them?

**Comment by saadeghi** [comment]
1. These are all color names: https://daisyui.com/docs/add-themes  
1. And these are the CSS variables assigned for each color: https://github.com/saadeghi/daisyui/blob/master/src/colors/colorNames.js  
1. And each theme sets its own HSL color values to the variables: https://github.com/saadeghi/daisyui/blob/master/src/colors/themes.js  
1. On this page there's a `preveiw` section that  shows some components but not all: https://daisyui.com/core/colors  

Your question is too general to answer. The easiest way to see which color a specific component is using would be looking at the CSS code on dev tools.  
Most components have obvious colors tho. For example if you look at `.btn-primary` style, it's:
```css
.btn-primary {
    --tw-bg-opacity: 1;
    background-color: hsla(var(--p) / var(--tw-bg-opacity,1));
    --tw-border-opacity: 1;
    border-color: hsla(var(--p) / var(--tw-border-opacity,1));
    --tw-text-opacity: 1;
    color: hsla(var(--pc) / var(--tw-text-opacity,1));
}
```
You can see according to [CSS variables](https://github.com/saadeghi/daisyui/blob/master/src/colors/colorNames.js) `--p` is `primary` and `--pc` is `primary-content`.

Also, there's [this theme builder](https://themes.ionevolve.com/) made by @marshallswain
