### DISCUSSION TITLE
Date Picker?

### DISCUSSION THREAD

**Discussion by Crypt0Jesus** [saadeghi/daisyui#619] [Q&A] [answered]
Any recommendations for a date picker that plays well with DaisyUI?  I'm currently using SvelteKit.

**Comment by saadeghi** [comment, marked as answer]
Any datepicker that allows CSS styling would be good and you just need to set a few colors.  
For example this one: https://date-picker-svelte.kasper.space/docs  

You can set daisyUI background color and foreground color to it like this:
```css
:root {
  --date-picker-background: hsl(var(--b1));
  --date-picker-foreground: hsl(var(--bc));
}
```
So it would look good on both dark themes and light themes.
Other datepicker libraries might not give you variables like this one but you can rewrite the css colors in most of them.

Let me know if you need more help.

**Reply by Crypt0Jesus** [reply]
I was thinking about this one.  Seems to have all the features I need.
https://mskocik.github.io/svelty-picker/

**Reply by saadeghi** [reply]
Looks good.  
This also gives custom CSS variables to set colors.

**Reply by Crypt0Jesus** [reply]
Thanks.  I got  svelty-picker to work.  Question, what does hal(var(--bc)) do?  Does it let me reference my theme already in DaisyUI?

**Reply by Crypt0Jesus** [reply]
Ok, I figured out what you mean.  Thanks!
```css
--sdt-primary: hsl(var(--pf));
--sdt-clear-color: hsl(var(--s));
--sdt-today-bg: hsl(var(--p));
--sdt-btn-bg-hover: hsl(var(--nf));
--sdt-bg-main: hsl(var(--b1));
--sdt-btn-header-bg-hover: hsl(var(--nf));
--sdt-color: hsl(var(--nc));
```

**Reply by saadeghi** [reply]
Yeah. It was typo. It's `hsl` 

See this table here https://daisyui.com/docs/colors/

**Reply by pguardiario** [reply]
just the basic html5 date input works fine for most things
<input type="date" class="input" data-theme="dark">

**Comment by afrifans** [comment]
This doesn't have range dates also

**Comment by officefish** [comment]
Any progress?!

**Reply by saadeghi** [reply]
Progress?

**Reply by officefish** [reply]
I meen do you have plans make date picker as daizyUI component as well?!

**Reply by saadeghi** [reply]
You can either use the standard HTML `<input type="date">` or use a JS package for it.  
daisyUI is CSS. I can't make a date picker with CSS.

**Reply by officefish** [reply]
Thank you for explanation!

**Comment by EvgeniiaVak** [comment]
With the newer version it's not `hsl` it's `oklch` that made it work. Here is my secondary color example (also with https://date-picker-svelte.kasper.space/docs )

```CSS
	:root {
		--date-picker-background: oklch(var(--s));
		--date-picker-foreground: oklch(var(--sc));
		--date-picker-highlight-border: oklch(var(--s));
		--date-picker-highlight-shadow: oklch(var(--s));
		--date-picker-selected-color: oklch(var(--s));
		--date-picker-selected-background: oklch(var(--p));
	}
```
