### DISCUSSION TITLE
Drawer mobile start from a smaller breakpoint

### DISCUSSION THREAD

**Discussion by elitenoire** [saadeghi/daisyui#795] [Q&A] [answered]
The ```drawer-mobile``` makes the drawer always visible from desktop (1024px breakpoint).

Is there a  way I can make the drawer visible from a smaller breakpoint for e.g. 768px breakpoint?
That is, drawer is toggleable from < 768px and always visible from >= 768px.

**Comment by saadeghi** [comment, marked as answer]
Currently it's only possible by adding some custom CSS:  
https://play.tailwindcss.com/7zidjfRKOc?file=css  
```css
@media (min-width: 768px) {
  .drawer-mobile > .drawer-toggle ~ .drawer-side > .drawer-overlay + * {
    transform: translateX(0px);
  }
}
```

I will try to make it possible on the next major version.  
I created a new issue for it here https://github.com/saadeghi/daisyui/issues/797
