### ISSUE TITLE
Possible to top-align step?

### ISSUE THREAD

**Issue by vnugent** [saadeghi/daisyui#1041]
The `li` step elements are fixed to center/middle vertical alignment if I increase the height of the content. 
Is there a way to top align each step (as indicated by the dotted circles)?

```html
        <ul className='steps step-secondary steps-vertical gap-y-4'>
          <li className='step'>
            <Step1 />
          </li>
          <li className='step'>
            <Step2 />
          </li>
          <li className='step'>
            <Step3 />
          </li>
          <li className='step'>
            <Step4 />
          </li>
          <li className='step'>
            <Step5 />
          </li>
        </ul>

```
<img width="403" alt="Screen Shot 2022-08-20 at 7 27 15 PM" src="https://user-images.githubusercontent.com/3805254/185759325-159ded55-3304-4172-bf20-4308f5bf48a6.png">

**Comment by saadeghi** [comment]
You can add this style:
```css
.steps-vertical .step {
  align-items: start;
}
.steps-vertical .step:after {
  align-self: start;
}
.steps-vertical .step:before {
  --tw-translate-y: -100%;
}
```

Let me know if you have any questions
