### ISSUE TITLE
add font-variation-settings support

### ISSUE THREAD

**Issue by ariaieboy** [saadeghi/daisyui#1064]
Hi I am using a variable font for my website and I set some utilities in my tailwindcss file like this:
```CSS
@layer utilities {
    .font-hairline {
        font-variation-settings: 'wght' 10;
        font-weight: 10;
    }

    .font-thin {
        font-variation-settings: 'wght' 100;
        font-weight: 100;
    }

    .font-extralight {
        font-variation-settings: 'wght' 200;
        font-weight: 200;
    }

    .font-light {
        font-weight: 300;
        font-variation-settings: 'wght' 300;
    }

    .font-normal {
        font-weight: 400;
        font-variation-settings: 'wght' 400;
    }

    .font-medium {
        font-weight: 500;
        font-variation-settings: 'wght' 500;
    }

    .font-semibold {
        font-weight: 600;
        font-variation-settings: 'wght' 600;
    }

    .font-bold {
        font-weight: 700;
        font-variation-settings: 'wght' 700;
    }

    .font-extrabold {
        font-weight: 800;
        font-variation-settings: 'wght' 800;
    }

    .font-black {
        font-weight: 900;
        font-variation-settings: 'wght' 900;
    }

    .font-extrablack {
        font-weight: 930;
        font-variation-settings: 'wght' 930;
    }

    .font-heavy {
        font-weight: 960;
        font-variation-settings: 'wght' 960;
    }

    .font-fat {
        font-weight: 990;
        font-variation-settings: 'wght' 990;
    }
}
```
but daisyui does not respect this setting I want to know that is there any way to change the font-* utilities in daysiui like the example above so we can use variable fonts?
