### ISSUE TITLE
Toast positioning classes not working with responsive prefixes

### ISSUE THREAD

**Issue by TClark1011** [saadeghi/daisyui#1107]
Responsive prefixes are not applying to the classes used to position toast.

I was able to recreate the bug in the tailwind playground ([link](https://play.tailwindcss.com/GOXC9sTVHx)). You can see that the button changes color responsively, but the toast does not change position, even though both are using the `md:` responsive prefix.

I understand that the base`toast` class is not intended to be responsive, but the documentation says that the positioning classes are.

**Comment by TClark1011** [comment]
Another note: I looked at the CSS that was generated in the linked tailwind playground, and for the component CSS, this block of code was at the bottom:

```css
   {
    top: auto;
    bottom: 0px;
    --tw-translate-y: 0px;
    transform: translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y));
  }
```

I think those styles are meant to be the responsive `toast-bottom` styles, but for some reason the selector is just blank
