### ISSUE TITLE
Themed Scrollbars

### ISSUE THREAD

**Issue by ctwhome** [saadeghi/daisyui#119]
It might be a good addition to add themed scrollbars that adapt to the selected global theme: 

I got it working with the simple CSS rules: 

```css
/* Scrollbar colors*/
/* width */
::-webkit-scrollbar {
  width: 10px;
}

/* Track */
::-webkit-scrollbar-track {
  background: #C4CAD4;
}

/* Handle */
::-webkit-scrollbar-thumb {
  background: #888;
}

/* Handle on hover */
::-webkit-scrollbar-thumb:hover {
  background: #666;
}
```

I just couldn't get the theme variables to work with it var(--b1) for example

**Comment by ctwhome** [comment]
oke I got it with \`hsla(var(--b1));\`

```css
/* Import with  */
/* @import './scrollbar-color.css';  */

:root {
  --scrollbarTrack: hsla(var(--b1));
  --scrollbarThumb: hsla(var(--b3));
  --scrollbarThumbHover: hsla(var(--p));
}
/* Scrollbar colors*/
/* width */
::-webkit-scrollbar {
  width: 12px;
}

/* Track */
::-webkit-scrollbar-track {
  background: var(--scrollbarTrack);
}

/* Handle */
::-webkit-scrollbar-thumb {
  background: var(--scrollbarThumb);
  border-radius: 3px
}

/* Handle on hover */
::-webkit-scrollbar-thumb:hover {
  background: var(--scrollbarThumbHover);
}
```
