### ISSUE TITLE
Card Side outputting invalid CSS

### ISSUE THREAD

**Issue by SeanLatimer** [saadeghi/daisyui#1231]
When I started trying to use Card Side, compiles started failing due to invalid CSS. There's some CSS being output with no selector at all, which is causing compilation failures.

This is what is being output by the use of `card-side`:
```css
   {
    width: 100%;
    height: 100%;
    object-fit: cover;
  }
```
