### ISSUE TITLE
Mobile drawer fills up the screen

### ISSUE THREAD

**Issue by azmy60** [saadeghi/daisyui#1246]
I use the drawer component for mobile screen from the docs. It works well but when I increase the base font size from css, the drawer fills up the entire screen and can't be closed.

```css
html {
  font-size: 18px;
}
```
