### ISSUE TITLE
using hover class in <tr> leads parcel+tailwindcss+daisyui to create bad CSS classes

### ISSUE THREAD

**Issue by tfc** [saadeghi/daisyui#1277]
Minimal reproducer repository: https://github.com/tfc/tailwindcss-hovertr

The relevant snippets:

I use a [`<tr class="hover">`](https://github.com/tfc/tailwindcss-hovertr/blob/main/src/index.html#L20) element as described in the documentation: https://daisyui.com/components/table/

Parcel then stumbles over the daisyui css components:

```
@parcel/transformer-css: Unsupported pseudo class or element: hovertr

  /tmp/tailwindcss-hovertr/src/index.css:4302:26
 ```

In the non-optimized output, the `hover` class for `tr` elements looks like this:

```
.table .hover\:hover:hovertr:hover th, .table .hover\:hover:hovertr:hover td, .table .hover\:hover:hovertr:nth-child(2n):hover th, .table .hover\:hover:hovertr:nth-child(2n):hover td {
  --tw-bg-opacity: 1;
  background-color: hsl(var(--b3, var(--b2)) / var(--tw-bg-opacity));
}
```

I am no CSS expert, but it seems like there is some whitespace missing?
Or is something in my reproducer repository bad?

**Comment by saadeghi** [comment]
This is invalid CSS as you mentioned.  

But I can't do anything about it.  
daisyUI is just CSS. And it's valid CSS.  
If the way build tools process the input CSS, breaks the result file, there's something wrong with the build tool.  

You might want to open an issue on the Parcel repo: https://github.com/parcel-bundler/parcel/issues

Expected CSS (Tailwind CSS engine or PostCSS result):
```css
.table tr.hover:hover th,
.table tr.hover:hover td,
.table tr.hover:nth-child(even):hover th,
.table tr.hover:nth-child(even):hover td {
  --tw-bg-opacity: 1;
  background-color: hsl(var(--b3, var(--b2)) / var(--tw-bg-opacity));
}
```
Broken CSS (`@parcel/transformer-css` result):
```css
.table .hover\:hover:hovertr:hover th,
.table .hover\:hover:hovertr:hover td,
.table .hover\:hover:hovertr:nth-child(2n):hover th,
.table .hover\:hover:hovertr:nth-child(2n):hover td {
  --tw-bg-opacity: 1;
  background-color: hsl(var(--b3, var(--b2)) / var(--tw-bg-opacity));
}
```

Let me know if you have any questions.
