### ISSUE TITLE
rounded-* classes don't work for buttons in button groups

### ISSUE THREAD

**Issue by massimans** [saadeghi/daisyui#1360]
Hi,
this code produces
```html
<div class="btn-group">
  <input class="btn-active btn rounded-full" value="Increment" type="button">
  <input class="btn rounded-full" value="Decrement" type="button">
</div>
<input class="btn rounded-full" value="Decrement" type="button">
```
![image](https://user-images.githubusercontent.com/1666152/201888176-df301c5b-382f-4190-8555-6423f5ae2850.png)

where i would expect this

![image](https://user-images.githubusercontent.com/1666152/201891437-e93c62c5-63f0-4a12-bdc3-2c79e66fcf05.png)
the only way to get around it is by setting `--rounded-btn` CSS variable instead of the  `rounded-*` utilities on button groups.

witch is ok but something like below would hard to do without custom CSS

![image](https://user-images.githubusercontent.com/1666152/201906311-ffe70f4b-0f19-4004-9e92-df6938655a1f.png)
i think it can be solved with some CSS trickery in `src/utilities/styled/button.css`
if you want a PR for this hit me up

**Comment by abhijitghogre** [comment]
Temporarily, until there is an official fix, you can do something like:

```css
.btn-group.separate > .btn {
    border-radius: var(--rounded-btn) !important;
}

.btn-group.separate-pills > .btn {
    border-radius: 9999px !important;
}
```

and use these classes in your html like:

```html
<div className="btn-group gap-4 separate-pills">
        <input
          type="radio"
          name="options"
          data-title="Red"
          className="btn"
        />
        <input
          type="radio"
          name="options"
          data-title="Green"
          className="btn"
        />
        <input
          type="radio"
          name="options"
          data-title="Magenta"
          className="btn"
        />
</div>
```

![Screenshot 2023-01-16 at 3 24 44 PM](https://user-images.githubusercontent.com/4900478/212649684-44c67519-93ce-468d-a14d-f421c35e1aa3.png)

**Comment by saadeghi** [comment]
What do you think about this idea: https://github.com/saadeghi/daisyui/discussions/1572

**Comment by massimans** [comment]
@abhijitghogre  thats what i changed in the lib to make it work
``` css
/* src/utilities/styled/button.css */
/* group */
.btn-group {
  .btn:not(:first-child):not(:last-child) {
    border-top-left-radius: 0;
    border-top-right-radius: 0;
    border-bottom-left-radius: 0;
    border-bottom-right-radius: 0;
  }
}
.btn-group:not(.btn-group-vertical),
.btn-group.btn-group-horizontal {
  .btn:first-child:not(:last-child) {
    @apply -ml-px -mt-0;
    border-top-right-radius: 0;
    border-bottom-right-radius: 0;
  }
  .btn:last-child:not(:first-child) {
    border-top-left-radius: 0;
    border-bottom-left-radius: 0;
  }
}
.btn-group.btn-group-vertical {
  .btn:first-child:not(:last-child) {
    @apply -ml-0 -mt-px;
    border-bottom-left-radius: 0;
    border-bottom-right-radius: 0;
  }
  .btn:last-child:not(:first-child) {
    border-top-left-radius: 0;
    border-top-right-radius: 0;
  }
}
```


> What do you think about this idea: #1572

while i like the change to the api i don't think this solves the issue in hand
