### ISSUE TITLE
Collapse in html-lists not working correctly

### ISSUE THREAD

**Issue by danielniccoli** [saadeghi/daisyui#1445]
When adding collapse to a menu, it works for the tabindex-machanic, but not for the input-machanic. The input-mechanic is broken in visual and function.

Here is a repro: https://play.tailwindcss.com/9fRhbqvZRH?layout=horizontal&size=898x676

![grafik](https://user-images.githubusercontent.com/2971735/208295473-517b1ac6-187e-4965-bbfe-2e741e70d97d.png)

**Comment by saadeghi** [comment]
Fixed on `2.46.0`. Thank you

**Comment by danielniccoli** [comment]
Great, this works now. However, there is no hover animation in the top-level item.

**Comment by danielniccoli** [comment]
And the size is different. Item 5 and 8 have a height of 36, while all other items have a height of 24.

**Comment by saadeghi** [comment]
Honestly, this was not predicted. So I used different heights for `.collapse` and menu item.  
I will make them the same size in the next major version. I can't fix it now because this change of size, may break some existing websites so It should be a breaking change on the next major release.

For now you can add this code to your CSS to make them look good together:  
https://play.tailwindcss.com/DyQu8dC2yd?size=834x676&file=css
```css
.menu .collapse-title, .menu .collapse > input[type="checkbox"] {
  min-height: auto;
}
.menu .collapse:hover .collapse-title {
  background-color: hsl(var(--bc) / 0.1);
}
```

**Comment by danielniccoli** [comment]
Thanks @saadeghi !

This worked kinda nice.

> I can't fix it now because this change of size, may break some existing websites so It should be a breaking change on the next major release.

That is understandable. I changed that part to implement a bit more tailwindy-syntax. With the help of your example, I also managed to remove the padding of the submenu, because I think that looks nicer.

I also added a bit of code to condense the submenu items, to make them more distinguishable from main menu items.

I need just a little more help. When you hover over a submenu item, the parent gets highlighted as well. I would like to only have the menu item highlighted that is hovered over. But I was unable to do this. Do you have a solution for this?

https://play.tailwindcss.com/E8XiXd2X4O?size=834x676&file=css

```css
.menu .collapse-title,
.menu .collapse>input[type="checkbox"] {
    @apply min-h-min;
}

.menu .collapse:hover .collapse-title {
    background-color: hsl(var(--bc) / 0.1);
}

/* Remove submenu padding */
.menu .collapse-content.menu {
    @apply p-0;
}

/* Condense submenu items */
.menu .collapse-content.menu li a {
    @apply py-1;
}
```
