### ISSUE TITLE
Outline on Safari doesn't apply radius

### ISSUE THREAD

**Issue by RemVN** [saadeghi/daisyui#1492]
Is there any workaround or remove outline and use border radius by default?

Safari:
![image](https://user-images.githubusercontent.com/34063162/211134171-e60babc6-ac96-4499-bb1f-a9cecd9fb766.png)

Chrome:
![image](https://user-images.githubusercontent.com/34063162/211134188-1ee8a2c3-d26b-4b26-a115-84c4619e1d7f.png)

**Comment by saadeghi** [comment]
This is fixed on the "Safari Technology Preview" release 157:
- https://bugs.webkit.org/show_bug.cgi?id=246192
- https://webkit.org/blog/13575/release-notes-for-safari-technology-preview-157/
And is expected to be available for everyone on the next Safari update (16.3)


But for now, as a workaround, you can use box-shadow like this:  
https://play.tailwindcss.com/pG0l3saKDb?file=css
```css
.input:focus {
  outline: none;
  @apply ring-2 ring-current ring-offset-2;
}
.input-primary:focus {
  @apply ring-primary;
}
```

The reason we're not using box-shadow for it by default, is that it's `outline`'s job and it should be independent from element's box shadow. If we use box shadow, people can't use Tailwind CSS's `shadow` utility class for it if they need because it will override the default box shadow.

Let me know if you have any questions.
