### ISSUE TITLE
bug: Drawer does not allow pages scroll to top in Safari. Using Svelte Kit with DaisyUI

### ISSUE THREAD

**Issue by feavel1** [saadeghi/daisyui#1578]
### What version of daisyUI are you using?

daisyui: 2.50.0

### Describe your issue

# When using 'drawer' class, safari won't scroll to top when opening another page

Here is the css copied directly from the daisy ui

```css
.drawer {
  display: grid;
  width: 100%;
  overflow: hidden;
  height: 100vh; // Issue right here, I disabled these lines in my code so it works
  height: 100dvh; // Issue right here
}
.drawer.drawer-end {
  direction: ltr;
}
.drawer.drawer-end > * {
  direction: rtl;
}
...
```

This is a bug that I found many people been asking about, that doesn't occur in other browsers such as Edge. 

## Work around

Here is a video demonstrating the bug, and a work around of the bug that I found.

https://user-images.githubusercontent.com/73105576/217013139-94a2ef86-33ce-4849-95e8-6ed192287b24.mp4

## Problem 

This seems like some issue going on in safari it self, but maybe there can be some work arounds in the css to solve the problem. I saw many people been asking this so I decided to create this post.

### What browsers are you seeing the problem on?

Safari

**Comment by feavel1** [comment]
## Full code solution

I just added this in my app.css.

```css
.drawer-new {
	display: grid;
	width: 100%;
	overflow: hidden;
	/* height: 100vh;
	height: 100dvh; */
}
.drawer-new.drawer-end {
	direction: ltr;
}
.drawer-new.drawer-end > * {
	direction: rtl;
}
.drawer-new.drawer-end > .drawer-toggle ~ .drawer-side > .drawer-overlay + * {
	--tw-translate-x: 100%;
	transform: translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate))
		skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x))
		scaleY(var(--tw-scale-y));
	justify-self: end;
}
.drawer-new.drawer-end > .drawer-toggle:checked ~ .drawer-side > .drawer-overlay + * {
	--tw-translate-x: 0px;
	transform: translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate))
		skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x))
		scaleY(var(--tw-scale-y));
}
[dir='rtl'] .drawer-new.drawer-end > .drawer-toggle ~ .drawer-side > .drawer-overlay + * {
	--tw-translate-x: -100%;
}
[dir='rtl'] .drawer-new.drawer-end > .drawer-toggle:checked ~ .drawer-side > .drawer-overlay + * {
	--tw-translate-x: 0px;
}
[dir='rtl'] .drawer-new.drawer-end > .drawer-toggle:checked ~ .drawer-content {
	--tw-translate-x: 0.5rem /* 8px */;
}
.drawer-new.drawer-end > .drawer-toggle:checked ~ .drawer-content {
	--tw-translate-x: -0.5rem /* -8px */;
	transform: translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate))
		skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x))
		scaleY(var(--tw-scale-y));
}
```
Commented out the height, and changed all the 'drawer' classes to 'drawer-new'. 

Hope it helps.

**Comment by feavel1** [comment]
## Full code solution

I just added this in my app.css.

```css
.drawer-new {
	display: grid;
	width: 100%;
	overflow: hidden;
	/* height: 100vh;
	height: 100dvh; */
}
.drawer-new.drawer-end {
	direction: ltr;
}
.drawer-new.drawer-end > * {
	direction: rtl;
}
.drawer-new.drawer-end > .drawer-toggle ~ .drawer-side > .drawer-overlay + * {
	--tw-translate-x: 100%;
	transform: translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate))
		skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x))
		scaleY(var(--tw-scale-y));
	justify-self: end;
}
.drawer-new.drawer-end > .drawer-toggle:checked ~ .drawer-side > .drawer-overlay + * {
	--tw-translate-x: 0px;
	transform: translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate))
		skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x))
		scaleY(var(--tw-scale-y));
}
[dir='rtl'] .drawer-new.drawer-end > .drawer-toggle ~ .drawer-side > .drawer-overlay + * {
	--tw-translate-x: -100%;
}
[dir='rtl'] .drawer-new.drawer-end > .drawer-toggle:checked ~ .drawer-side > .drawer-overlay + * {
	--tw-translate-x: 0px;
}
[dir='rtl'] .drawer-new.drawer-end > .drawer-toggle:checked ~ .drawer-content {
	--tw-translate-x: 0.5rem /* 8px */;
}
.drawer-new.drawer-end > .drawer-toggle:checked ~ .drawer-content {
	--tw-translate-x: -0.5rem /* -8px */;
	transform: translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate))
		skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x))
		scaleY(var(--tw-scale-y));
}
```
Commented out the height, and changed all the 'drawer' classes to 'drawer-new'. 

Hope it helps.
