### ISSUE TITLE
bug: dropdown elements have wrong border-radius when tailwind prefix is used

### ISSUE THREAD

**Issue by desprit** [saadeghi/daisyui#1629]
### What version of daisyUI are you using?

2.50.1

### Describe your issue

Menu items have the following css rules:
```
.menu[class*=" px-"]:not(.menu[class*=" px-0"]) li>*, .menu[class^=px-]:not(.menu[class^=px-0]) li>*, .menu[class*=" p-"]:not(.menu[class*=" p-0"]) li>*, .menu[class^=p-]:not(.menu[class^=p-0]) li>*
```

I'm using `tw` prefix in my tailwind config and padding rules look like `tw-p-X` so the above rules don't work.
![Screenshot 2023-02-22 at 18 08 57](https://user-images.githubusercontent.com/4673543/220663694-7b7a1328-9828-4542-bed7-047a34b38c40.png)

### What browsers are you seeing the problem on?

Chrome

**Comment by saadeghi** [comment]
This is really hard to fix.  
A quick workaround is adding this style to your CSS:   
```css
.menu[class^="tw-p-"]:not(.menu[class^="tw-p-0"]) li>* {
    border-radius: var(--rounded-btn,.5rem);
}
```
The problem is, I can't read Tailwind's prefix config. So I can only use a selector like this:  
```css
.menu[class*="p-"]:not(.menu[class*="p-0"]) li>* {
    border-radius: var(--rounded-btn,.5rem);
}
```
But above style is dangerous because it targets any class name that has the `p-` string inside it (like `top-*` or `gap-*`)  

It's hard for daisyUI to apply the `prefix` config of Tailwind to this specific CSS rule because daisyUI source files are CSS files and it would cost adding new Post CSS dependencies to read the prefix config and apply it to the CSS files.

I will try to find a way to fix it...
