### ISSUE TITLE
bug: avatar ring classes don't get the prefix

### ISSUE THREAD

**Issue by jaimeiniesta** [saadeghi/daisyui#1721]
### What version of daisyUI are you using?

v2.51.5

### Describe your issue

I'm using DaisyUI with a prefix:

```
daisyui: {
  prefix: "d-"
}
```

So, all my DaisyUI classes begin with `d-`, for example `d-avatar`. But in the case of `ring-primary`, the generated class name is not getting the prefix, it should be `d-ring-primary` but it's still `ring-primary`.

The same happens with other "ring" classes:

```css
.d-avatar {
  position: relative;
  display: inline-flex;
}

.d-avatar > div {
  display: block;
  aspect-ratio: 1 / 1;
  overflow: hidden;
}

.d-avatar img {
  height: 100%;
  width: 100%;
  -o-object-fit: cover;
     object-fit: cover;
}

...

.ring-primary {
  --tw-ring-opacity: 1;
  --tw-ring-color: hsl(var(--p) / var(--tw-ring-opacity));
}

.ring-success {
  --tw-ring-opacity: 1;
  --tw-ring-color: hsl(var(--su) / var(--tw-ring-opacity));
}

.ring-secondary {
  --tw-ring-opacity: 1;
  --tw-ring-color: hsl(var(--s) / var(--tw-ring-opacity));
}
```
