### ISSUE TITLE
bug: Daisyui themes not working properly with nextjs 13 app folder

### ISSUE THREAD

**Issue by kumosal** [saadeghi/daisyui#1723]
### What version of daisyUI are you using?

v2.51.5

### Describe your issue

I'm using nextjs 13 with app directory + [theme-change](https://github.com/saadeghi/theme-change)
the background color changes but the font color  doesn't change when I toggle the themes (light/dark).
Check it here : https://next13-app-chi.vercel.app
repo: https://github.com/kumosal/next13-app

### What browsers are you seeing the problem on?

Chrome, Safari, Other

### Reproduction URL (optional)

https://next13-app-chi.vercel.app

**Comment by saadeghi** [comment]
I can't see the repo (maybe it's private) but I can see that you have another CSS file which is applying colors to the page:
```css
:root {
    --max-width: 1100px;
    --border-radius: 12px;
    --font-mono: ui-monospace,Menlo,Monaco,"Cascadia Mono","Segoe UI Mono","Roboto Mono","Oxygen Mono","Ubuntu Monospace","Source Code Pro","Fira Mono","Droid Sans Mono","Courier New",monospace;
    --foreground-rgb: 0,0,0;
    --background-start-rgb: 214,219,220;
    --background-end-rgb: 255,255,255;
    --primary-glow: conic-gradient(from 180deg at 50% 50%,#16abff33 0deg,#0885ff33 55deg,#54d6ff33 120deg,#0071ff33 160deg,transparent 360deg);
    --secondary-glow: radial-gradient(#fff,hsla(0,0%,100%,0));
    --tile-start-rgb: 239,245,249;
    --tile-end-rgb: 228,232,233;
    --tile-border: conic-gradient(#00000080,#00000040,#00000030,#00000020,#00000010,#00000010,#00000080);
    --callout-rgb: 238,240,241;
    --callout-border-rgb: 172,175,176;
    --card-rgb: 180,185,188;
    --card-border-rgb: 131,134,135;
}
```
```css
body {
    color: rgb(var(--foreground-rgb));
    background: linear-gradient(to bottom,transparent,rgb(var(--background-end-rgb))) rgb(var(--background-start-rgb))
}
```
These styles are not from daisyUI or Tailwind CSS (by default). If you don't need them you should find that CSS file and remove/unlink it
