### ISSUE TITLE
How to set theme parameters in tailwind.config.js working with CDN importing? docs: 

### ISSUE THREAD

**Issue by JTorresConsulta** [saadeghi/daisyui#1858]
### Describe the issue

I am using the CDN import of Daisy UI for development.

According to this documentation page: https://daisyui.com/docs/config/
When I set the parameters of my theme in the "tailwind.config.js" file and import it to my .html navigator launch the error: 

`Uncaught ReferenceError: module is not defined at tailwind.config.js:1:1`

How could I solve it?
Thank you in advance !

### What browsers are you seeing the problem on?

Chrome

**Comment by saadeghi** [comment]
The error is probably because you're trying to import a commonjs file as a ES module.  
But why are you trying to import the Tailwind config file to your HTML?  
Tailwind CSS works at build time. It only generates a CSS file and you should just import the CSS file.

**Comment by JTorresConsulta** [comment]
Hello @saadeghi 

I am developing with a simple HTML editor and the navigator.
I import Daisy Ui and Tailwind like the next:

https://daisyui.com/docs/cdn/

```
<link href="https://cdn.jsdelivr.net/npm/daisyui@3.0.0/dist/full.css" rel="stylesheet" type="text/css" />
<script src="https://cdn.tailwindcss.com"></script>
```

If I import "tailwind.config.js" file navigator launch that error.
If "tailwind.config.js" is not imported nothing occurrs when "mytheme" is setted

`<html data-theme="mydark"> ...`

How could I create my own theme?
Thanks !!

**Comment by saadeghi** [comment]
`tailwind.config.js` is not needed when you're using the CDN. It's for when you installed the NPM package and you want to generate the CSS file in the build time.

Using, CDN, there is no build step. so you can't add daisyUI as a plugin to Tailwind CSS config and you won't be able to change [daisyUI config](https://daisyui.com/docs/config/). The CDN file is basically a large file with all possible classnames.

If you really have to use the CDN for production (which is not recommended) one way to define custom themes is defining your themes like this: https://unpkg.com/browse/daisyui@3.0.0/dist/themes.css  
For example this is the built-in `light` theme:
```css
[data-theme=light] {
    color-scheme: light;
    --pf: 259 94% 44%;
    --sf: 314 100% 40%;
    --af: 174 75% 39%;
    --nf: 214 20% 14%;
    --in: 198 93% 60%;
    --su: 158 64% 52%;
    --wa: 43 96% 56%;
    --er: 0 91% 71%;
    --inc: 198 100% 12%;
    --suc: 158 100% 10%;
    --wac: 43 100% 11%;
    --erc: 0 100% 14%;
    --rounded-box: 1rem;
    --rounded-btn: 0.5rem;
    --rounded-badge: 1.9rem;
    --animation-btn: 0.25s;
    --animation-input: .2s;
    --btn-text-case: uppercase;
    --btn-focus-scale: 0.95;
    --border-btn: 1px;
    --tab-border: 1px;
    --tab-radius: 0.5rem;
    --p: 259 94% 51%;
    --pc: 259 96% 91%;
    --s: 314 100% 47%;
    --sc: 314 100% 91%;
    --a: 174 75% 46%;
    --ac: 174 75% 11%;
    --n: 214 20% 21%;
    --nc: 212 19% 87%;
    --b1: 0 0% 100%;
    --b2: 0 0% 95%;
    --b3: 180 2% 90%;
    --bc: 215 28% 17%
}
```
The numbers in CSS variables are HSL values of the colors.  
And here is the reference for the names: https://daisyui.com/docs/colors/ For example `--p` is for `primary`

Let me know if you had any questions.
