### ISSUE TITLE
bug: RTL drawer is messed up

### ISSUE THREAD

**Issue by CripyIce** [saadeghi/daisyui#2034]
### What version of daisyUI are you using?

3.1.5

### Describe your issue

After upgrading to 3.1.15, the drawer in RTL versions is always visible.
The drawer also comes from the left side while it should be coming from the **right** side.

### What browsers are you seeing the problem on?

Chrome and Safari

### Reproduction URL (optional)

https://play.tailwindcss.com/1Vj1TO1ezs

**Comment by haghft** [comment]
the problem is  `translateX(-100%)`
This rule must be change from:
```css
 [dir=rtl] .drawer-side>:not(.drawer-overlay){
      transform: translateX(-100%);
    }
```
to:
```css
 [dir=rtl] .drawer-side>:not(.drawer-overlay){
      transform: translateX(100%);
    }
```
