### ISSUE TITLE
bug: Menu with title as a parent have active style

### ISSUE THREAD

**Issue by maxscharwath** [saadeghi/daisyui#2125]
### What version of daisyUI are you using?

v3.2.1

### Describe your issue

```jsx
<ul className="menu bg-base-200 w-56 rounded-box">
  <li>
    <h2 className="menu-title">Title</h2>
    <ul>
      <li><a>Item 1</a></li>
      <li><a>Item 2</a></li>
      <li><a>Item 3</a></li>
    </ul>
  </li>
</ul>
```

When clicking on `<h2/>` an active background is applied, i dont think it's supposed to be. 

### What browsers are you seeing the problem on?

Chrome

### Reproduction URL

https://daisyui.com/components/menu/#menu-with-title-as-a-parent

**Comment by maxscharwath** [comment]
There are a missing `:not(.menu-title)` here:

```css
.menu li>*:not(ul):not(details):active,.menu li>*:not(ul):not(details).active,.menu li>details>summary:active {
    --tw-bg-opacity: 1;
    background-color: hsl(var(--n)/var(--tw-bg-opacity));
    --tw-text-opacity: 1;
    color: hsl(var(--nc)/var(--tw-text-opacity))
}
```
