### ISSUE TITLE
bug: semantic colour utility classes not working

### ISSUE THREAD

**Issue by JamesMcNee** [saadeghi/daisyui#2384]
### What version of daisyUI are you using?

v3.8.2

### Describe your issue

The semantic colour utility classes (as described in https://daisyui.com/docs/colors/) e.g. `bg-base-100` are not working as they output invalid CSS.

E.g. 
```css
.bg-base-100 {
    background-color: hsl(var(--b1) / <alpha-value>);
}
```

If I replace the `alpha-value` here with a number (e.g. 100) then they work fine.

Doing a little bit of sleuthing I think this likely broke when all this code was commented out: https://github.com/saadeghi/daisyui/blob/c2a0ac2bbec1f24fd730ad5edebab953ba274f88/src/full/tailwind.config.js#L39-L62

### What browsers are you seeing the problem on?

Chrome
