### ISSUE TITLE
Sticky Navigation Bar in Drawer?

### ISSUE THREAD

**Issue by SkillzGamingYT** [saadeghi/daisyui#248]
How do I make my navigation bar sticky (fixed - always stay at the top) when it's placed inside a drawer?

My sticky-nav code seems to break after putting it inside the drawer.

```css
.nav-sticky {
    position: fixed !important;
    top: 0 !important;
    width: 100% !important;
    z-index: 99 !important;
}
```
