### ISSUE TITLE
Add some padding to badge with text inside an indicator

### ISSUE THREAD

**Issue by matronator** [saadeghi/daisyui#276]
_EDIT: Browser used is Safari 14.0.3 on macOS 11.2.3._

Just discovered this project and while looking through the components I noticed that the text inside indicators doesn't really fit inside the badge and it's too cramped there or just straight up overflowing. This is what I mean:

<img width="274" alt="Snímek obrazovky 2021-10-30 v 14 37 12" src="https://user-images.githubusercontent.com/5470780/139533707-f679321f-6cd0-49d0-9bad-434a189471aa.png">
<img width="431" alt="Snímek obrazovky 2021-10-30 v 14 57 34" src="https://user-images.githubusercontent.com/5470780/139533709-440bd0fe-56aa-446c-9238-31b5af3fe4ba.png">

I had a quick look at the CSS in devtools and thought this might do the trick (pure CSS for now, no Tailwind directives):

```css
/* The `:not(:empty)` selector is there so empty badges without any text
   wouldn't be affected (they get "squashed" without it). */
.indicator .indicator-item.badge:not(:empty) {
  box-sizing: content-box; /* without it, the paddings won't work */
  padding-left: 4px;
  padding-right: 4px;
}
```

This is what it looks with these changes:

<img width="193" alt="Snímek obrazovky 2021-10-30 v 15 01 33" src="https://user-images.githubusercontent.com/5470780/139533840-18a4deb0-475f-4eba-88a6-c0b8e5441d30.png">
<img width="435" alt="Snímek obrazovky 2021-10-30 v 15 01 38" src="https://user-images.githubusercontent.com/5470780/139533842-e92dc61b-6ea6-42c9-9d04-f6c58e9d0747.png">

I would open a PR, but don't know where exactly would I put this snippet since it contains two different components. Would it go to `badge.css` or `indicator.css` or somewhere else entirely?
