### ISSUE TITLE
bug: collapse element selectable from closed dropdown content

### ISSUE THREAD

**Issue by Hydhen** [saadeghi/daisyui#2761]
### What version of daisyUI are you using?

4.6.0

### Which browsers are you seeing the problem on?

Chrome, Edge

### Reproduction URL

https://play.tailwindcss.com/n2mMKEEkuQ

### Describe your issue

Hello!

I try to combine an accordion inside a dropdown like so:

```html
<div class="dropdown">
  <div tabindex="0" role="button" class="btn m-1">Click</div>
  <div tabindex="0" class="dropdown-content menu z-[1] w-52 rounded-box bg-base-100 p-2 shadow">
    <ul>
      <li>
        <div class="collapse bg-base-200">
          <input type="radio" name="my-accordion-1" checked="checked" />
          <div class="collapse-title text-xl font-medium">Click to open this one and close others</div>
          <div class="collapse-content">
            <p>hello</p>
          </div>
        </div>
      </li>
      ...
    </ul>
  </div>
</div>
```

My problem is that I can click on the collapse title and content while the dropdown is closed, from what I've seen that rule seems to be the problem:

```css
.collapse:not(td):not(tr):not(colgroup) {
    visibility: visible;
}
```

**Comment by Hydhen** [comment]
Here's how I fixed it so far:

```css
/* Dropdown compatibility */
.dropdown:not(:focus-within) .collapse,
.dropdown:not(:focus-within) .collapse > * {
  visibility: collapse !important;
}
```

I'm forced to use the `!important` here because without it the rule gets overridden by this very specific one:

```css
.collapse[open] > .collapse-content, .collapse-open > .collapse-content,
.collapse:focus:not(.collapse-close) > .collapse-content,
.collapse:not(.collapse-close) > input[type=checkbox]:checked ~ .collapse-content,
.collapse:not(.collapse-close) > input[type=radio]:checked ~ .collapse-content {
    visibility: visible;
    min-height: fit-content;
}
```
