### ISSUE TITLE
Multilevel dropdown

### ISSUE THREAD

**Issue by rallisf1** [saadeghi/daisyui#281]
This must be really simple but I can't figure it out lol.

Anyone care to share an example with multilevel dropdown using the dropdown component?

**Comment by saadeghi** [comment]
I can add this feature but with a cost of functionality:
> currently we can have a `<div class="dropdown">` wrapper and where ever there's a `dropdown-content` inside, it will work. (no matter if it's a direct child or a grandchild, etc...)
If we support multi-level dropdowns, CSS should be like `.dropdown:focus>.dropdown-content` and it will only target the direct child.

That will a breaking change. Also, multi-level dropdown is a bad UX practice anyway, so I don't think it's a good trade off.

**Comment by rallisf1** [comment]
Too bad it won't be implemented. I finally figured it out though, with a few compromises (can't have a gap between menus, had to replace padding with border...)

I had to overwrite a few css
```css
.dropdown .dropdown-left > .dropdown-content,  .dropdown .dropdown-right > .dropdown-content {
    opacity: 0;
    visibility: hidden;
    padding-left: inherit;
}
.dropdown .dropdown-left:hover > .dropdown-content, .dropdown .dropdown-right:hover > .dropdown-content {
    opacity: 1;
    visibility: visible;
}
.dropdown .menu {
    overflow: visible;
}
```
Obviously when having a vertical menu you will only expand left or right.
Here is the complete code on [playground ](https://play.tailwindcss.com/8olaeXicjB) but for some reason it's not working as on my svelte project (same code runs flawlessly, must be a css scope thing), I only replaced font-awesome icons with &gt; and &lt;

Hope someone finds it helpful.
