### ISSUE TITLE
How do I change the color of the checkbox?

### ISSUE THREAD

**Issue by rohaanhamid** [saadeghi/daisyui#311]
I want to apply a color not in the DaisyUI theme. How do I apply it to the checkbox? Just applying "bg-black" does not work.

**Comment by saadeghi** [comment]
@rohaanhamid you need to set `--chkbg` CSS variable for checkbox background color and `--chkfg` for checkbox foreground color.  
Example: https://play.tailwindcss.com/h8luyB8bOt?file=css

let me know if you have any questions

**Comment by anhsirk0** [comment]
```css
.checkbox-error {
  --chkbg: 350 89.2% 60.2%; /* HSL color values for rose[500] */
  --chkfg: 0 100% 100%; /* HSL color values for white */
}

.checkbox-error:checked {
  border-color: hsl(350 89.2% 60.2%); /* HSL color values for rose[500] */
}
```

Also set border-color (on checked) to match the backgroundg color.
