### ISSUE TITLE
bug: DaisyUI 5: `<html data-theme="light">` doesn't work when there's `prefersdark: true;`

### ISSUE THREAD

**Issue by lts20050703** [saadeghi/daisyui#3253]
### What version of daisyUI are you using?

5.0.0-alpha.29

### Which browsers are you seeing the problem on?

All browsers

### Reproduction URL

https://play.tailwindcss.com/pFadUDJMTg

### Describe your issue

`<html data-theme="light">` doesn't work when there's `prefersdark: true;`

app.css

```css
@import "tailwindcss";

@plugin "daisyui" {
	themes: light, dark;
}

@plugin "daisyui/theme" {
	name: "light";
	default: true;
}

@plugin "daisyui/theme" {
	name: "dark";
	prefersdark: true;
}
```

Strangely, `<html data-theme="dark">` still works when there's `prefersdark: true;`. 

I checked the generated CSS and found that `prefers-color-scheme: dark` is after `[data-theme="light"]`. This makes it impossible for `[data-theme="light"]` to override `prefers-color-scheme: dark`.

`data-theme="dark"` still works because it's after `prefers-color-scheme: dark`, therefore able to override `prefers-color-scheme: dark`.

TL;DR: Current generated CSS order:
- Root theme
- prefers-color-scheme: dark
- Other themes

Fixing this should be a simple reorder to
- prefers-color-scheme: dark
- Root theme
- Other themes

In other words, https://github.com/saadeghi/daisyui/blob/dfec9ea0f91552ff348b1e7dc0c26432ae2064d3/src/theming/functions.js#L214 needs to inject `prefers-color-scheme: dark` before injecting the root theme.
