### ISSUE TITLE
bug: table-zebra class not applying background color as expected

### ISSUE THREAD

**Issue by algowhiz** [saadeghi/daisyui#3275]
### What version of daisyUI are you using?

v4.0.3

### Which browsers are you seeing the problem on?

Chrome

### Reproduction URL

https://play.tailwindcss.com/8cZeWJ3aSo?file=css

### Describe your issue

The table-zebra class is not applying the expected background color in an alternating row pattern due to conflicts with custom color settings in the project. This affects readability as the alternating background colors do not appear as intended.

Expected Behavior: The table-zebra class should display distinct background colors on alternate rows, overriding custom colors to ensure consistent styling for better readability.

Actual Behavior: Due to custom color definitions, the background color for alternate rows is not applied as expected. Applying an !important flag to the table-zebra row colors could potentially resolve this issue.

// Apply alternating background colors to table-zebra rows 

.table-zebra tbody tr:nth-child(odd) {
  background-color: #f9fafb !important;  //light
}

.table-zebra tbody tr:nth-child(even) {
  background-color: #e5e7eb !important;  //dark
}

**Comment by euglv** [comment]
> https://play.tailwindcss.com/8cZeWJ3aSo?file=css

You forget 
```
  plugins: [require('daisyui')],
```
in the tailwind config. 
Removing `!important` from your custom css changes nothing in the output.

**Comment by AerisG222** [comment]
not sure if this is the same thing you are running into, but looking at styled.css in the latest daisyui (4.12.14), you can see the following:

```css
.table-zebra tr.active,
    .table-zebra tr.active:nth-child(even),
    .table-zebra-zebra tbody tr:nth-child(even) {
    --tw-bg-opacity: 1;
    background-color: var(--fallback-b3,oklch(var(--b3)/var(--tw-bg-opacity)))
}
```

if you add the `table-zebra-zebra` class, do you get the striping you expect?

I realize this is a workaround, but I was looking into something similar in my project and came across this...


Hope this helps,
Mike
