### ISSUE TITLE
problem with form toggle on rtl...

### ISSUE THREAD

**Issue by TgMrP** [saadeghi/daisyui#33]
have problem on toggle class when dir="rtl"

in the class is
```css
.toggle~.toggle-mark {
    justify-content: flex-start;
}
```

but in rtl need to be
```css
.toggle~.toggle-mark {
    justify-content: flex-end;
}
```

how can i change this?
