### ISSUE TITLE
using daisyUI with svelte-flatpickr

### ISSUE THREAD

**Issue by amiracam** [saadeghi/daisyui#345]
warning newbie,
I was able to integrate it with a svelte form however, the accompanying css for flatpickr does not work with the daisy dark theme that I'm using, I understand I can override the accompanying css for flatpickr but wonder if there's a more "daisy" way of doing this ? 

thanks

**Comment by saadeghi** [comment]
@amiracam flatpickr is a component with custom HTML/CSS. It comes with a CSS file and when you import the CSS file, It applies the style for the datepicker elements. for example this is the style for "day" box and you can see it comes with colors and other styles:
```css
.flatpickr-day {
    background: none;
    border: 1px solid transparent;
    border-radius: 150px;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
    color: #393939;
    cursor: pointer;
    font-weight: 400;
    width: 14.2857143%;
    -webkit-flex-basis: 14.2857143%;
    -ms-flex-preferred-size: 14.2857143%;
    flex-basis: 14.2857143%;
    max-width: 39px;
    height: 39px;
    line-height: 39px;
    margin: 0;
    display: inline-block;
    position: relative;
    -webkit-box-pack: center;
    -webkit-justify-content: center;
    -ms-flex-pack: center;
    justify-content: center;
    text-align: center;
}
```
And every color applies from that CSS file. Unfortunately there's no way to add some Tailwind (or daisyUI) utility classes to adapt the theme colors. You need to rewrite the color values coming from the CSS file of the plugin.  
For example, you can change the. background color of calendar to daisyUI's theme background color like this:
```css
.flatpickr-calendar{
  background: hsl(var(--b1));
}
```
or you can change the text color of "day" box like this:
```css
.flatpickr-day{
  color: hsl(var(--bc));
}
```
It takes time to manually change the colors of every section if you want it to fully adapt theme colors.
