### ISSUE TITLE
bug: (v5) Collapse doesn't work when compiled with postcss

### ISSUE THREAD

**Issue by Joxeur2** [saadeghi/daisyui#3466]
### What version of daisyUI are you using?

5.0.0-beta.6

### Which browsers are you seeing the problem on?

Chrome

### Reproduction URL

https://github.com/Joxeur2/tailwind-test/tree/feature/daisyui

### Describe your issue

I'm migrating my Angular application to Daisyui 5, but I'm having a problem with the collapse. When I click on the collapse, it opens, but I can't see the content...

<img width="576" alt="Image" src="https://github.com/user-attachments/assets/886be63f-13d3-4c54-b02c-af911148373b" />

I've created a minimal setup where I reproduce the issue:

https://github.com/Joxeur2/tailwind-test/tree/feature/daisyui

I can see that it works on the site, and I also have the latest version of the Nexus template where it works as well.

I've tried to investigate, even though my Tailwind knowledge is very limited, and here's what I've observed:

If I set "**minify: false**" in the Nexus project's Vite config and run "**npm build**", I get the following in CSS output:

- Nexus App:

```css
.collapse:is([open], .collapse-open, :focus:not(.collapse-close)) > .collapse-content, .collapse:not(.collapse-close) > :where(input:is([type="checkbox"], [type="radio"]):checked ~ .collapse-content) {
    visibility: visible;
    min-height: fit-content;
}
```

Whereas when I run "**npm run build:dev**" in my Angular test project, I get:

- Angular App:

```css
.collapse:is(:is([open], .collapse-open, :focus:not(.collapse-close)) > .collapse-content, :not(.collapse-close) > :where(input:is([type=checkbox], [type=radio]):checked ~ .collapse-content)) {
    visibility: visible;
    min-height: fit-content;
}
```

The generated CSS is not the same. In fact, when I explicitly copy-paste the CSS from "Nexus App", the collapse works.

I feel that the code generated by tailwind/vite and tailwind/postcss is not the same. It's as if there's a syntax error in the base code that is interpreted differently by tailwind/vite and tailwind/postcss.

In fact, I tried generating the CSS with tailwind/cli and, at the location of the CSS rule, IntelliJ tells me that a comma is missing.

<img width="852" alt="Image" src="https://github.com/user-attachments/assets/b4afe1c4-199a-493b-9911-c13c433e1fb7" />
