### ISSUE TITLE
bug: (v5) Date, time, and datetime inputs aren't styled correctly in Safari

### ISSUE THREAD

**Issue by Plonq** [saadeghi/daisyui#3519]
### What version of daisyUI are you using?

5.0.0-beta.8

### Which browsers are you seeing the problem on?

Safari

### Reproduction URL

https://v5.daisyui.com/components/input/

### Describe your issue

The text inside date/time inputs is not styled correctly in Safari (screenshots taken from https://v5.daisyui.com/components/input/):

![Image](https://github.com/user-attachments/assets/e1faf616-6c87-471c-ae96-6e553d2d0a2d)

![Image](https://github.com/user-attachments/assets/212485fc-8d05-4b64-afb7-79c262e38d4d)

### Detailed Explanation

It seems that `display: inline-block` is causing the misaligned text. This is fixable by setting `line-height: var(--size);`, but that makes the selection background color full height. A better fix is to make the wrapper element full height and then use flex to align the text center.

The text colour can be fixed to be overriding the `-webkit-text-fill-color` property of the pseudo-elements:

```
-webkit-datetime-edit-year-field
-webkit-datetime-edit-month-field
-webkit-datetime-edit-day-field
-webkit-datetime-edit-hour-field
-webkit-datetime-edit-minute-field
-webkit-datetime-edit-second-field
-webkit-datetime-edit-meridiem-field
```

There's also the highlight colour when a segment is selected:

![Image](https://github.com/user-attachments/assets/62f489e9-9711-4e72-93ac-f5dfd70f3c76)

This is controlled with the `background-color` property of each segment.

### Proposed Fix

Putting all that together, the following CSS fixes the time input:

```css
input[type="time"] {
    
  &::-webkit-datetime-edit {
    height: 100%;
  }
  
  &::-webkit-datetime-edit-fields-wrapper {
    display: flex;
    align-items: center
  }

  &::-webkit-datetime-edit-hour-field,
  &::-webkit-datetime-edit-minute-field,
  &::-webkit-datetime-edit-second-field,
  &::-webkit-datetime-edit-meridiem-field {
    -webkit-text-fill-color: var(--color-base-content);
  }
  
  &::-webkit-datetime-edit-hour-field:focus,
  &::-webkit-datetime-edit-minute-field:focus,
  &::-webkit-datetime-edit-second-field:focus,
  &::-webkit-datetime-edit-meridiem-field:focus {
    background-color: var(--color-accent);
    -webkit-text-fill-color: var(--color-accent-content);
  }
}
```

How it looks:

![Image](https://github.com/user-attachments/assets/62535d73-0567-47da-809c-3ebcf588eed6)

![Image](https://github.com/user-attachments/assets/74ff142d-ee57-4713-9391-00934a193dc5)

### Final Thoughts

I'm happy to open a PR, but I am unsure whether the above fix fits in with Daisy's design/architecture overall. Especially the choice of color for the selection highlight background.

This only targets webkit selectors and so does not affect other browsers. That said, it might be worth customising the selection highlight color in other browsers too, for consistency (if that's possible).
