### ISSUE TITLE
bug: --color-* and --color-*-content variable override inside @theme does not work

### ISSUE THREAD

**Issue by rafaeljacov** [saadeghi/daisyui#3580]
### What version of daisyUI are you using?

5

### Which browsers are you seeing the problem on?

Firefox, Edge

#### I USE THE CDN VERSION OF DAISYUI
```css
/* input.css */

/* THIS WORKS */
:root {
    --color-error: #e94134;
    --color-error-content: #fff;
}

@theme {
    --color-primary: #0095ff;
    --color-secondary: #dddddd;
    --color-dark: #252525;
    --color-success: #48a64c;
    /* --color-error: #e94134; DOES NOT WORK */
    /* --color-error-content: #fff; DOES NOT WORK */
    --color-line: #848484;

    --font-poppins: "Poppins", sans-serif;
    --font-public-sans: "Public Sans", sans-serif;
}
```
```html
<head>
        <link href="https://cdn.jsdelivr.net/npm/daisyui@5" rel="stylesheet" type="text/css"/>
	<script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
<head/>

<form id="expense-form" class="flex flex-wrap gap-2">
	<input type="text" id="expense-name" placeholder="Expense Name" required/>
	<input type="number" id="expense-amount" placeholder="Amount" required/>
	<button type="submit" class="btn btn-error btn-lg">Add Expense</button>
</form>
```
