### ISSUE TITLE
bug: !important needed to override some styles in DaisyUI

### ISSUE THREAD

**Issue by withden** [saadeghi/daisyui#3657]
In some cases, DaisyUI styles require important overrides, which can cause issues when customizing styles. 

If you've faced similar issues where DaisyUI styles are difficult to override, please comment below with the class. We will add into this list

**Bug List**

- [ ] Badge (`badge badge-outline !border-base-300`)

**Comment by PruthviPraj00** [comment]
Hello @withden,

The reason for this is that in Tailwind V4, the `addComponents` function now places the CSS under `@layer utilities`.

![Image](https://github.com/user-attachments/assets/a20dbac7-9de7-44f9-b878-324fa5b91909)

As for the DaisyUI style for badges, the border color of the outline badge uses the current text color. Instead of modifying the border, you should adjust the text color like this:

```
text-base-300
```

This issue will persist until Tailwind Labs decides to revert the changes. @saadeghi has also raised this issue in Tailwind:  
[https://github.com/tailwindlabs/tailwindcss/issues/15045](https://github.com/tailwindlabs/tailwindcss/issues/15045)

**Comment by CoderJo-Pro** [comment]
Yes! This is also what I ran into. I just came from https://github.com/tailwindlabs/tailwindcss/issues/15045, wish this could be fixed as fast as they could. I override the `.btn` class of v5, made it `hover:scale-95` and `translate-none`. If I let it go with the `utilities` layer, it just won't override.

```css
@import "tailwindcss";
@plugin "daisyui";

@layer base, components, utilities, daisyui-override;

@layer daisyui-override {
  .btn {
    @apply translate-none;

    transition: scale 0.1s ease-in-out;
    
    &:hover {
      @apply active:scale-95;
    }
  }

  & .btn-ghost {
    /* --btn-ghost-bg: oklch(from var(--color-base-content) l c h / calc(alpha - 0.8)); */
    --btn-ghost-bg: color-mix(in oklab, var(--color-base-content), transparent 80%);

    &:hover {
      --btn-bg: color-mix(in oklab, var(--btn-color, var(--btn-ghost-bg)), black 7%);
    }

    &:active:not(.btn-active) {
      --btn-bg: color-mix(in oklab, var(--btn-color, var(--btn-ghost-bg)), black 5%);
      --btn-border: color-mix(in oklab, var(--btn-color, var(--btn-ghost-bg)), black 7%);
    }
  }
}

```
