### ISSUE TITLE
bug: Tailwind Dark Selector not working

### ISSUE THREAD

**Issue by yogeshbabu** [saadeghi/daisyui#3677]
### Reproduction URL (Required)

localhost

### What version of daisyUI are you using?

v5.0.4

### Describe your issue

Trying to implement dark mode toggle. found multiple issues trying solve it.

1. Hydration issue, even though i check mount state with useEffect still throwing Hydration error.
2.  if i put --prefersdark and use toggle after. Doesn't work. it doesn't toggle. stays constant on dark mode.
3. using tailwind darkmode dark: selector. Doesn't work. elements where i use dark: to override stays on light theme

Except for #1 i followed everything from documentation. Any Suggestion for #1 will be appreciated as well.

I am using all latest packages Vite, Tanstack router, react, tailwind

**Comment by saadeghi** [comment]
> Hydration issue, even though i check mount state with useEffect still throwing Hydration error.

This can not be related to daisyUI.  
daisyUI and Tailwind CSS are both dev-dependencies. The only thing comes out of daisyUI and Tailwind CSS is a single CSS file which is created at build-time, not runtime.

> if i put --prefersdark and use toggle after. Doesn't work. it doesn't toggle. stays constant on dark mode.

What do you mean "toggle after"? Can you share a reproduction link?  

> using tailwind darkmode dark: selector. Doesn't work

You don't need `dark:` anymore. That's the point of using semantic color names.  
Read more: https://daisyui.com/docs/colors/

`dark:` variant works for `prefers-color-scheme: dark` as before. daisyUI doesn't change anything about that, but daisyUI also adds a new way to change themes using `data-theme` HTML attribute. If you want to extend Tailwind's `dark:` variant to support `data-theme` as well, here's how: https://daisyui.com/docs/themes/#-5


Let me know if you have a question.

**Comment by yogeshbabu** [comment]
Hydration we can ignore as the load changes from SSR to Client, was checking in to see if anyone have some close issue.

Unable to share enterprise code... basically what we have is like this...
**global.css**
```
@plugin "daisyui" {
  themes:
    fantasy --default,
    dracula;
  exclude: rootscrollgutter;
  logs: false;
}
```
if i put --prefersafter next to dracula then use then using the toggle component not changing theme. We do have useState and useEffect to handle changes
```
<input
        type="checkbox"
        title="Dark Mode Toggle"
        className="toggle toggle-secondary theme-controller"
        checked={darkState}
        value={themeMode}
      />
```

for the dark selector... we did add
```
@custom-variant dark (&:where([data-theme=dracula], [data-theme=dracula] *));
```
example drawer udpate
```
```

we have override some of the classes for dark and light mode as built in colors doesn't match what we want. so when the dark toggle does click

**Comment by saadeghi** [comment]
1. Change it like this  

```diff
@plugin "daisyui" {
-  themes: fantasy --default, dracula;
+  themes: fantasy --default, dracula --prefersdark;
  exclude: rootscrollgutter;
  logs: false;
}
```
Docs: https://daisyui.com/docs/config/#themes

2. Instead of `bg-white dark:bg-base-200` just use `bg-base-200`. As I said, you don't need to set colors for `dark:` anymore. daisyUI colors change automatically when you change the theme.

Docs: https://daisyui.com/docs/colors/


Let me know if you have any questions

**Comment by topherfangio** [comment]
I noticed that setting the theme via the theme-controller (like using a checkbox on the page) would set the theme to dark, but would **not** utilize the `dark:` variant.

I updated my config to account for this by creating a custom dark variant that does what Tailwind originally does AND allows you to use the theme controller.

```css
/* Import the base Tailwind theme */
@import 'tailwindcss';

/* Include our custom plugins */
@plugin '@tailwindcss/typography';
@plugin 'daisyui' {
  themes: light --default, dark --prefersdark, synthwave, retro, cyberpunk, wireframe;
};

/* Setup standard dark: variant to work for both System-based & DaisyUI Theme-based dark mode */
@custom-variant dark (@media (prefers-color-scheme: dark), :root:has(input.theme-controller[value=dark]:checked) &);
```

That said, I ultimately took @saadeghi's advice and just used `text-base-content/70` instead of trying to actually _use_ the dark variant 🤷‍♂
