### ISSUE TITLE
bug: Tabs can't be made to fit full height within other tabs

### ISSUE THREAD

**Issue by cretucosmin3** [saadeghi/daisyui#3685]
### Reproduction URL (Required)

https://play.tailwindcss.com/oCfC7QXw0E

### What version of daisyUI are you using?

5.0.0

### Which browsers are you seeing the problem on?

Firefox

### Describe your issue

You can't have tabs that take full height of the parent tab without overflowing.

![Image](https://github.com/user-attachments/assets/e7bcee5b-321e-4cac-bc62-dfd506a08794)

**Comment by cretucosmin3** [comment]
@saadeghi thanks for coming back so quickly.

That was exactly the issue I was trying to highlight, you can't make tabs take full height of the parent.

When I came across this I was using the tabs in a grid, I don't want to have a scroll, it's just how my app is designed, instead I'd like the height of (tabs + content) to be full height of the parent.

Here's an example of what I mean + solution (adding a class `tabs-h-full`)
https://play.tailwindcss.com/7hDOxgOn8A

The solution:
``` CSS
.tabs {
  &.tabs-h-full {
    height: 100%;

    --tab-height-multiplier: 10;

    > .tab-content {
      height: calc(100% - calc(var(--size-field, 0.25rem) * var(--tab-height-multiplier)));
    }

    &.tabs-xs {
      --tab-height-multiplier: 6;
    }

    &.tabs-sm {
      --tab-height-multiplier: 8;
    }

    &.tabs-md {
      --tab-height-multiplier: 10;
    }

    &.tabs-lg {
      --tab-height-multiplier: 12;
    }

    &.tabs-xl {
      --tab-height-multiplier: 14;
    }
  }
}
```

The solution is just to calculate the full height - height of tabs, also taking into account the different size variants.

I'd make a PR but the repo is really large, it's downloading few gb...
