### ISSUE TITLE
Tailwind CSS: The `text-primary` class does not exist

### ISSUE THREAD

**Issue by leapofazzam123** [saadeghi/daisyui#377]
Hi, I'm trying to customize the DaisyUI components in a seperate CSS file, but I got this:
```
3:04:43 PM [vite] Internal server error: /data/data/com.termux/files/home/leap-website/src/app.css:144:5: The `text-primary` class does not exist. If `text-primary` is a custom class, make sure it is defined within a `@layer` directive.
  Plugin: vite:css
  File: /data/data/com.termux/files/home/leap-website-sveltekit/src/app.css
  142|
  143|    .link:hover {
  144|      @apply text-primary font-semibold;
     |       ^
  145|      background-size: 0% 1.275px, 100% 1.275px;
  146|    }
      at Input.error (/data/data/com.termux/files/home/leap-website-sveltekit/node_modules/postcss/lib/input.js:148:16)
      at AtRule.error (/data/data/com.termux/files/home/leap-website-sveltekit/node_modules/postcss/lib/node.js:60:32)
      at processApply (/data/data/com.termux/files/home/leap-website-sveltekit/node_modules/tailwindcss/lib/lib/expandApplyAtRules.js:187:33)
      at /data/data/com.termux/files/home/leap-website-sveltekit/node_modules/tailwindcss/lib/lib/expandApplyAtRules.js:315:9
      at /data/data/com.termux/files/home/leap-website-sveltekit/node_modules/tailwindcss/lib/processTailwindFeatures.js:45:50                                                        at plugins (/data/data/com.termux/files/home/leap-website-sveltekit/node_modules/tailwindcss/lib/index.js:20:104)
      at LazyResult.runOnRoot (/data/data/com.termux/files/home/leap-website-sveltekit/node_modules/postcss/lib/lazy-result.js:339:16)
      at LazyResult.runAsync (/data/data/com.termux/files/home/leap-website-sveltekit/node_modules/postcss/lib/lazy-result.js:393:26)
      at async compileCSS (/data/data/com.termux/files/home/leap-website-sveltekit/node_modules/vite/dist/node/chunks/dep-76613303.js:20426:27)
      at async TransformContext.transform (/data/data/com.termux/files/home/leap-website-sveltekit/node_modules/vite/dist/node/chunks/dep-76613303.js:20015:50)
```

**Comment by saadeghi** [comment]
@leapofazzam123 Hey, can you please provide a small GitHub repo so I can reproduce this?

**Comment by leapofazzam123** [comment]
I can't but this is my tailwind.config.js
```js
const config = {
  content: ["./src/**/*.{html,js,svelte,ts}"],
  plugin: [require("daisyui")],
  theme: {
    extend: {
      animation: {
        "gradient-x": "gradient-x 15s ease infinite",
        "gradient-y": "gradient-y 15s ease infinite",
        "gradient-xy": "gradient-xy 15s ease infinite"
      },
      keyframes: {
        "gradient-y": {
          "0%, 100%": {
            "background-size": "400% 400%",
            "background-position": "center top"
          },
          "50%": {
            "background-size": "200% 200%",
            "background-position": "center center"
          }
        },
        "gradient-x": {
          "0%, 100%": {
            "background-size": "200% 200%",
            "background-position": "left center"
          },
          "50%": {
            "background-size": "200% 200%",
            "background-position": "right center"
          }
        },
        "gradient-xy": {
          "0%, 100%": {
            "background-size": "400% 400%",
            "background-position": "left center"
          },
          "50%": {
            "background-size": "200% 200%",
            "background-position": "right center"
          }
        }
      }
    }
  }
}

module.exports = config
```
And this is my CSS file
```css
@import url("https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,100..900;1,100..900&family=Knewave&display=swap");

@tailwind base;
@tailwind components;
@tailwind utilities;

@font-face {
  font-family: "Twemoji";
  src: url("/font/twemoji.woff2") format("woff2"), url("/font/twemoji.woff") format("woff"),
    url("/font/twemoji.ttf") format("truetype"),
    url("/font/twemoji.eot#iefix") format("embedded-opentype");
  unicode-range: U+1F300-1F5FF, U+1F600-1F64F, U+1F680-1F6FF, U+2600-26FF;
}

h1 {
  @apply text-3xl;
}

h2 {
  @apply text-2xl;
}

h3 {
  @apply text-xl;
}

h4 {
  @apply text-lg;
}

h5 {
  @apply text-base;
}

h6 {
  @apply text-sm;
}

h1,
h2,
h3,
h4,
h5,
h6 {
  @apply font-bold block;
}

blockquote,
dd,
dl,
h1,
h2,
h3,
h4,
h5,
h6,
hr,
figure,
p,
pre {
  @apply block mb-2;
}

html,
body {
  @apply transition-colors duration-150;
  font-family: "Public Sans", "Twemoji", sans-serif;
  line-height: 1.525em;
}

@layer components {
  .branding {
    @apply text-primary-content font-normal;
    font-family: "Knewave", sans-serif;
    text-shadow: 0.065em 0.05275em 0.125em #000000;
  }

  .bg-branding {
    @apply w-full;
    background: linear-gradient(340deg, #00a2dd, #00baff, #74d9ff);
    background-size: 150% 200%;
    -webkit-animation: bg-gradient-animate 25s ease infinite;
    -moz-animation: bg-gradient-animate 25s ease infinite;
    -o-animation: bg-gradient-animate 25s ease infinite;
    animation: bg-gradient-animate 25s ease infinite;
  }

  @-webkit-keyframes bg-gradient-animate {
    0% {
      background-position: 0% 81%;
    }
    50% {
      background-position: 100% 20%;
    }
    100% {
      background-position: 0% 81%;
    }
  }

  @-moz-keyframes bg-gradient-animate {
    0% {
      background-position: 0% 81%;
    }
    50% {
      background-position: 100% 20%;
    }
    100% {
      background-position: 0% 81%;
    }
  }

  @-o-keyframes bg-gradient-animate {
    0% {
      background-position: 0% 81%;
    }
    50% {
      background-position: 100% 20%;
    }
    100% {
      background-position: 0% 81%;
    }
  }

  @keyframes bg-gradient-animate {
    0% {
      background-position: 0% 81%;
    }
    50% {
      background-position: 100% 20%;
    }
    100% {
      background-position: 0% 81%;
    }
  }

  .link {
    @apply font-medium bg-no-repeat transition-all duration-300;
    background-image: linear-gradient(to right, hsl(var(--bc)), hsl(var(--bc))),
      linear-gradient(to right, hsl(var(--p)), hsl(var(--p)));
    background-position: 100% 100%, 0% 100%;
    background-size: 100% 1.275px, 0% 1.275px;
  }

  .link:hover {
    @apply text-primary font-semibold;
    background-size: 0% 1.275px, 100% 1.275px;
  }
}
```
