### ISSUE TITLE
bug: --input-color variable is not used

### ISSUE THREAD

**Issue by 0xtlt** [saadeghi/daisyui#3788]
### Reproduction URL (Required)

https://github.com/0xtlt/bug-daisy

### What version of daisyUI are you using?

^5.0.20

### Which browsers are you seeing the problem on?

All browsers

### Describe your issue

In my theme css config:
I tried to change the value of --input-color as mentioned in [the DaisyUI documentation](https://daisyui.com/docs/utilities/) but the value is not used and always fallback on this value:
![Image](https://github.com/user-attachments/assets/3582c18c-a261-4fd9-b7ff-78dc546640ff)

I've created a reproducible env you can install with bun and run, hope this helps.

Thank you for your work!

**Comment by saadeghi** [comment]
This is expected behavior.  
`--input-color` is a "Component specific CSS variable" so the value is defined at the component, not globally at theme level.  
So setting the value at theme, won't override the value of the component

Try this:
```css
.input {
  --input-color: var(--color-base-300);
}
```

Let me know if you have a question.

**Comment by thnee** [comment]
Thanks, that's very helpful!

As another example, I was able to modify the background of `menu`, and add transparency, by doing this:

```css
.menu {
	--menu-active-bg: color-mix(in srgb, var(--color-primary) 50%, transparent);
}
```

At first I tried putting this code in `@layer components` which didn't work.
But when this code is at the top level of `main.css`, outside of any layers, it does work.
Not sure exactly why, just hoping that this is expected.
