### ISSUE TITLE
bug: Text Input placeholder color not properly applied

### ISSUE THREAD

**Issue by mathisvester** [saadeghi/daisyui#3870]
### Reproduction URL (Required)

https://branch-from-task.netlify.app

### What version of daisyUI are you using?

v5.0.35

### Which browsers are you seeing the problem on?

All browsers

### Describe your issue

When comparing the placeholder color of the Text Input component from the [daisyUI docs](https://daisyui.com/components/input/) with my local Angular project, there's a discrepancy in how the ::placeholder color is rendered.

In my Angular project, the CSS rule for ::placeholder is correctly generated with color-mix, but the browser (Chrome) does not apply it. In Chrome DevTools, it resolves to `color: currentColor;` instead of the intended mixed value. However, on the daisyUI documentation site, the placeholder appears correctly with the mixed color and Chrome DevTools displays the color rule `color: color-mix(in oklab, currentColor 50%, transparent);` as expected.

I can confirm this behaviour in mobile Safari and Firefox, too.

<img width="429" alt="Text Input local" src="https://github.com/user-attachments/assets/691c3e21-f24c-4af2-ae3e-1d162bc248c1" />
<img width="329" alt="Text Input docs" src="https://github.com/user-attachments/assets/84a732a9-e8fe-4848-8bca-534f5f53c7c2" />

**Comment by mathisvester** [comment]
Temporary fixed it by applying styles manually and replacing `currentColor` with actual color:

```
::placeholder {
    color: color-mix(in oklab, #100f0f 50%, transparent);
}
```

**Comment by saadeghi** [comment]
Can you share a minimal reproduction link where I can see the issue please?

**Comment by mathisvester** [comment]
@saadeghi created a new [reproduction URL](https://cute-alpaca-84ef4e.netlify.app)

**Comment by mikerooni** [comment]
I've managed to fix this using the following workaround so that it stays theme-aware:

```css
@plugin "daisyui/theme" {
    ...
    
    --color-base-placeholder: color-mix(in oklab, currentColor 50%, transparent);
}

::placeholder {
    color: var(--color-base-placeholder);
}
```

If I skip the variable and use `color: color-mix(in oklab, currentColor 50%, transparent)` directly, it stops working.

As to why this is the case, I honestly have no idea - maybe it's simply an edge case in how most browsers parse CSS...

**Comment by pdanpdan** [comment]
I think you should check what is the list of supported browsers used when building. I think you have some browsers that do not support `color-mix` in the list, and you hit a tailwind bug.

You can test simply by adding a simple `<input class="placeholder-red-300" />` and see if it renders as expected.

**Comment by pdanpdan** [comment]
@mikerooni @mathisvester any feedback? Can this be closed, or can you add details?

**Comment by mathisvester** [comment]
@pdanpdan when I'm opening the reproduction url in my mobile Safari v18 I'm facing the same issue. I currently havn't got time to test other browsers, but this Safari version should be supported right: [https://tailwindcss.com/docs/compatibility](https://tailwindcss.com/docs/compatibility)?

**Comment by pdanpdan** [comment]
The normal CSS that is compiled for `placeholder` is:

```CSS
@supports (not ((-webkit-appearance: -apple-pay-button))) or (contain-intrinsic-size:1px) {
  ::placeholder {
    color:currentColor
  }

  @supports (color: color-mix(in lab,red,red)) {
    ::placeholder {
      color:color-mix(in oklab,currentcolor 50%,transparent)
    }
  }
}
```

In your reproduction you have:

```CSS
@supports (not (-webkit-appearance: -apple-pay-button)) or (contain-intrinsic-size: 1px) {
  ::placeholder {
    color:currentcolor
  }

  @supports (color: color-mix(in lab,red,red)) {
    {
      color:color-mix(in oklab,currentcolor 50%,transparent)
    }
  }
}
```

So it must be some CSS processor/post-processor you are using that breaks the output.

I'm sorry but if you don't provide any details on your tools it's hard to help you fix your tools chain.

I can guess it's something like this: https://github.com/tailwindlabs/tailwindcss/issues/16147#issuecomment-2629318357 (check all thread)
