### ISSUE TITLE
bug: Nested @property causes PostCSS build warnings

### ISSUE THREAD

**Issue by brianhelba** [saadeghi/daisyui#3882]
### Reproduction URL (Required)

https://github.com/brianhelba/parcel-tailwind-postcss/tree/daisy-build

### What version of daisyUI are you using?

5.0.35

### Describe your issue

When built, daisyUI's `@property --radialprogress` is nested within a `@layer base` with the overall structure:
```css
@layer base {
  @property --radialprogress {
    syntax: "<percentage>";
    inherits: true;
    initial-value: 0%;
  }
}
```

However, [Parcel](https://parceljs.org/) (a popular tool for building with PostCSS) [expects that](https://github.com/parcel-bundler/lightningcss/issues/968):
> `@property` is only valid at the top level, not inside a layer

This causes builds of Tailwind + daisyUI with Parcel to emit the warning:
```
@parcel/transformer-css: Unknown at rule: @property
```

---

Given than the effects of registering a `@property` are indeed global (it's meaningless to scope to a `@layer`), could the definition of `@property --radialprogress` be moved to the top level (just like all the other `@property --tw-border-style`, etc.)?
