### ISSUE TITLE
bug: Floating Label overlays the drawer component

### ISSUE THREAD

**Issue by kensodemann** [saadeghi/daisyui#3929]
### Reproduction URL (Required)

https://github.com/kensodemann/show-floating-labels

### What version of daisyUI are you using?

5.0.43

### Which browsers are you seeing the problem on?

All browsers

### Describe your issue

I have an application that has some forms using floating labels. I also have a drawer menu to the left. On smaller form factors, this drawer is opened via a hamburger menu. If this takes place while there is data in the inputs, and thus the labels are floating, they float above the drawer.

I have reproduced this in a simple app. To replicate, run the (see instructions in README.md file), fill in some of the inputs so at least one of the labels floats, then open the drawer using the hamburger menu. You should see the floating labels float above the menu.

Inputs with the labels floating:
<img width="526" alt="Image" src="https://github.com/user-attachments/assets/58139bd2-16f1-4a75-9282-cb90c47a5c6f" />

Labels floating over the drawer:
<img width="569" alt="Image" src="https://github.com/user-attachments/assets/3da1db8d-512f-48f8-bde9-7f0abd98d156" />

I noticed the floating labels use a `z-index` of `2`, and removing that solves _this_ issue, but I have no idea if it causes other issues.

```css
.floating-label {
    &:focus-within, &:not(:has(input:placeholder-shown, textarea:placeholder-shown)) {
        > span {
            opacity: 100%;
            top: 0;
            translate: -12.5% calc(-50% - 0.125em);
            scale: 0.75;
            pointer-events: auto;
            z-index: 2;
        }
    }
}
```

**Comment by sulimanbenhalim** [comment]
@saadeghi assign this to me

**Comment by sulimanbenhalim** [comment]
if removing the z-index:2 this is what it causes:

<img width="109" alt="Image" src="https://github.com/user-attachments/assets/a8d0996c-5082-4a23-b556-8d85789cc3ff" />

so I increased the z-index of the drawer

**Comment by cabrace** [comment]
<img width="1924" height="622" alt="Image" src="https://github.com/user-attachments/assets/563b120c-4571-4b6a-a9ba-c3a29c31195a" />




**Problem**: class="border-collapse table table-pin-rows" causes pinned heading bleedthrough with drawer.

**DaisyUI Version**: 	"daisyui": "^5.0.43",
**Browser >  Chrome**: Version 131.0.6778.108 (Official Build) (64-bit) 

It *could* just very well be my browser version, which I DO need to update. But just posting as I do notice this.

```css
.table {
    :where(.table-pin-rows thead tr) {
        position: sticky;
        top: calc(0.25rem* 0);
        z-index: 1; /** Changing z-index here to zero fixes issue **/
        background-color: var(--color-base-100);
    }
}


```
