### ISSUE TITLE
bug: JANKY animation on closing modal

### ISSUE THREAD

**Issue by thednp** [saadeghi/daisyui#3946]
### Reproduction URL (Required)

https://daisyui.com/components/modal/

### What version of daisyUI are you using?

5.0.43

### Which browsers are you seeing the problem on?

Chrome

### Describe your issue

When you close a modal, you always get a JANKY animation (the dialog jumps left about 15px, the exact size of a scrollbar), which is horrible UX.

THE DEFINITIVE FIX:

instead of using 

```css
.modal {
  overflow-x: hidden;
  overflow-y: hidden;
  overscroll-behavior: contain;
}
```

you can instead do this
```css
.modal {
  scroll-gutter: auto;
  overscroll-behavior: contain; /* this should be optional IMO, but I don't know what this tries to fix/cover */
}
```

`scroll-gutter: auto;` should fix any and all JANKY behaviours with popups and such. Try it let me know.

**Comment by thednp** [comment]
Same as #3942

**Comment by Damix48** [comment]
Hi, I tried what you suggested but it didn't work for me. Can you share a complete example?

**Comment by thednp** [comment]
@Damix48 go to [Modal Page](https://daisyui.com/components/modal/) and edit the CSS for the `.modal` add the following rule `scrollbar-gutter: auto` then toggle this rule ON/OFF, open modals and close them, you'll see the difference immediately.

**Comment by Damix48** [comment]
@thednp Thank you.
I was trying this:
```css
@plugin "daisyui" {
  exclude: rootscrollgutter;
}
```
After disabling it, your solution works perfectly.
