### ISSUE TITLE
bug: [v5] No practical way to globally customize font-size - terrible DX compared to v4

### ISSUE THREAD

**Issue by astralski** [saadeghi/daisyui#3975]
**What version of daisyUI are you using?**
v5.0.43

**Which browsers are you seeing the problem on?**
All browsers (CSS/design issue)

**Describe your issue:**

DaisyUI v5 has made font-size customization unnecessarily difficult and provides poor developer experience.

### The Problem

1. **Default font sizes are too small** - Many components now feel cramped compared to v4
2. **No global control** - There's no CSS variable to control font-size globally (only `--size-field` for height/padding)
3. **Manual override hell** - To change font sizes, developers must override EVERY component class individually

### Current Required Workaround

To get reasonable font sizes, I have to write CSS like this:

```css
.btn { font-size: 1rem !important; }
.btn-xs { font-size: 0.75rem !important; }
.btn-sm { font-size: 0.875rem !important; }
.btn-md { font-size: 1rem !important; }
.btn-lg { font-size: 1.125rem !important; }
.btn-xl { font-size: 1.25rem !important; }

.input { font-size: 1rem !important; }
.input-xs { font-size: 0.75rem !important; }
.input-sm { font-size: 0.875rem !important; }
.input-md { font-size: 1rem !important; }
.input-lg { font-size: 1.125rem !important; }
.input-xl { font-size: 1.25rem !important; }

.select { font-size: 1rem !important; }
.select-xs { font-size: 0.75rem !important; }
.select-sm { font-size: 0.875rem !important; }
.select-md { font-size: 1rem !important; }
.select-lg { font-size: 1.125rem !important; }
.select-xl { font-size: 1.25rem !important; }

.textarea { font-size: 1rem !important; }
.textarea-xs { font-size: 0.75rem !important; }
.textarea-sm { font-size: 0.875rem !important; }
.textarea-md { font-size: 1rem !important; }
.textarea-lg { font-size: 1.125rem !important; }
.textarea-xl { font-size: 1.25rem !important; }

/* And potentially dozens more components... */
```

This is **terrible developer experience**.

### What DaisyUI v4 Did Right

- Default font size was 16px (1rem) - worked well in 90% of cases
- If customization was needed, simple CSS overrides worked without `!important`
- Developers rarely needed to touch font sizes

### What I Expected from v5

One of these solutions:

**Option 1: Better defaults**
```css
/* Just use good defaults like v4 had */
/* Most developers won't need to customize */
```

**Option 2: CSS variable control**
```css
@plugin "daisyui/theme" {
  name: "mytheme";
  --font-size-xs: 0.75rem;
  --font-size-sm: 0.875rem;
  --font-size-md: 1rem;
  --font-size-lg: 1.125rem;
  --font-size-xl: 1.25rem;
}
```

**Option 3: Single scale variable**
```css
@plugin "daisyui/theme" {
  name: "mytheme";
  --font-scale: 1.2; /* Makes all fonts 20% larger */
}
```

### Why This Matters

- **Font size is basic customization** - One of the first things developers want to adjust
- **Current system doesn't scale** - Large projects with many components become maintenance nightmare
- **Discourages adoption** - Developers will avoid DaisyUI if basic customization is this painful
- **Breaks component philosophy** - Components should be easy to use AND customize

### Current State

DaisyUI v5 introduced tokenization for many aspects (colors, spacing) but **completely missed font-size**. This feels like an oversight rather than intentional design.

## Expected Behavior

Font size should be as easy to customize as colors are - either through good defaults or simple CSS variables.
