### ISSUE TITLE
Toggle/checkbox don't change state in winicss

### ISSUE THREAD

**Issue by xorik** [saadeghi/daisyui#443]
Hi.

For some reason it's impossible to enable checkbox/toggle when I use windicss 😞 

Here's demo: https://stackblitz.com/edit/vite-tcwtbf?file=index.html

**Comment by saadeghi** [comment]
Windi is generating invalid style.
Expected CSS is:
```CSS
.toggle:checked,.toggle[checked=true]{
  --chkbg:hsl(var(--bc));
  --tw-bg-opacity:1;
  --tw-border-opacity:1;
  box-shadow:var(--handleoffset) 0 0 2px hsl(var(--b1)) inset, 0 0 0 2px hsl(var(--b1)) inset, var(--focus-shadow);
}
```
What Windi generates:
```CSS
toggle, .toggle[checked=true] {
  --chkbg: hsl(var(--bc));
  --tw-bg-opacity: 1;
  --tw-border-opacity: 1;
  box-shadow: var(--handleoffset) 0 0 2px hsl(var(--b1)) inset, 0 0 0 2px hsl(var(--b1)) inset, var(--focus-shadow);
}
```
I suggest using Tailwind CSS instead of Windi
