### ISSUE TITLE
Button Ghost active and hover state is not working properly with Windi CSS

### ISSUE THREAD

**Issue by vineryap** [saadeghi/daisyui#461]
Hi,
I'm using the latest version of Windi CSS and daisyUI.

`windi.config.ts` config
```js
import { defineConfig, transform } from 'windicss/helpers';
import daisyUiColors from 'daisyui/colors/windi';

export default defineConfig({
	extract: {
		include: ['./src/**/*.{html,js,svelte,ts}']
	},
	plugins: [transform('daisyui')],
	theme: {
		extend: {
			colors: daisyUiColors
		}
	}
});
```
![button-ghost](https://user-images.githubusercontent.com/82420632/154058247-a4053df7-07c9-4744-ac69-eed4c5f1a692.gif)

**Comment by saadeghi** [comment]
I can't do anything about it. Windi CSS is generating invalid style by skipping a few lines.

Source style that daisyUI is providing
```js
".btn-ghost": {
  "borderWidth": "1px",
  "borderColor": "transparent",
  "backgroundColor": "initial",
  "color": "currentColor"
},
".btn-ghost.btn-active,.btn-ghost:hover": {
  "-TwBorderOpacity": "0",
  "-TwBgOpacity": ["1", "0.2"],
  "backgroundColor": "hsl(var(--bc) / var(--tw-bg-opacity))"
},
".btn-ghost:focus-visible": {
  "outline": "2px 0 0 2px solid currentColor"
},
```

Expected CSS (the output that Tailwind CSS generates)
```css
.btn-ghost {
   border-width: 1px;
   border-color: transparent;
   background-color: initial;
   color: currentColor;
}

.btn-ghost.btn-active,.btn-ghost:hover {
   --tw-border-opacity: 0;
   --tw-bg-opacity: 0.2;
   background-color: hsl(var(--bc) / var(--tw-bg-opacity));
}

.btn-ghost:focus-visible {
   outline: 2px 0 0 2px solid currentColor;
}
```

The output that Windi CSS generates:
```css
.btn-ghost {
  border-width: 1px;
  border-color: transparent;
  background-color: initial;
  color: currentColor;
}
.btn-ghost:focus-visible {
  outline: 2px 0 0 2px solid currentColor;
}
```

Please open an issue on Windi CSS repo.
