### ISSUE TITLE
Make button click animation/wiggle a separate class

### ISSUE THREAD

**Issue by xcorat** [saadeghi/daisyui#493]
It would be nice if we can add the button transitions to other elements like **Card** or an `<a>`. We can add the `btn` class, but that adds too many other classes that I don't need.

I'm know there must be a way to do it manually, but I haven't been able to figure out. I think a similar request was made earlier at #225.

**Comment by xcorat** [comment]
Huh! ok, this works. Guess I can close this (?)

```
    .clickable:active {
        transform:scale( var(--btn-focus-scale, .95) )
    }
```

**Comment by saadeghi** [comment]
This is the style:
```css
.card {
  animation: button-pop var(--animation-btn, 0.25s) ease-out;
  transition-property: color,background-color,border-color,text-decoration-color,fill,stroke,opacity,box-shadow,transform,filter,backdrop-filter,-webkit-text-decoration-color,-webkit-backdrop-filter;
  transition-duration: .2s;
  transition-timing-function: cubic-bezier(.4,0,.2,1);
}
.card:active:focus, .card:active:hover {
  animation: none;
  transform: scale(var(--btn-focus-scale,.95));
}
```
https://play.tailwindcss.com/2OCCAHe0KH?file=css

If this was available as a separate class, it would end up with unnecessary duplication and I don't think it's a usual need to use button animation on other elements. I think it's better to manually extract and use the style for cases like this.
