### ISSUE TITLE
Input indicator misplaced when uses a datalist

### ISSUE THREAD

**Issue by rinodrummer** [saadeghi/daisyui#726]
When a `.input` element has the attribute `[list]` will be showed an selection indicator (&#9660;) that is misplaced.

This style should fix the issue: 

```css
.input[list]::-webkit-calendar-picker-indicator {
  line-height: 1em;
}
```

I would have contributed directly with a pull request but was unsure where to place my style.
