### ISSUE TITLE
How to use DaisyUI colors in plugin `typography`

### ISSUE THREAD

**Issue by hrenaud** [saadeghi/daisyui#735]
Is it a way to override `typography` default colors in `tailwind.config.js` (like `--tw-prose-headings`) with colors set in `daisyui` theme ?

**Comment by saadeghi** [comment]
By default, `@tailwindcss/typography` colors will be overridden like this:  
```css
:root .prose {
  --tw-prose-body: hsla(var(--bc)/.8);
  --tw-prose-headings: hsl(var(--bc));
  --tw-prose-lead: hsl(var(--bc));
  --tw-prose-links: hsl(var(--bc));
  --tw-prose-bold: hsl(var(--bc));
  --tw-prose-counters: hsl(var(--bc));
  --tw-prose-bullets: hsla(var(--bc)/.5);
  --tw-prose-hr: hsla(var(--bc)/.2);
  --tw-prose-quotes: hsl(var(--bc));
  --tw-prose-quote-borders: hsla(var(--bc)/.2);
  --tw-prose-captions: hsla(var(--bc)/.5);
  --tw-prose-code: hsl(var(--bc));
  --tw-prose-pre-code: hsl(var(--nc));
  --tw-prose-pre-bg: hsl(var(--n));
  --tw-prose-th-borders: hsla(var(--bc)/.5);
  --tw-prose-td-borders: hsla(var(--bc)/.2);
}
```

This allows us to have a good contrast and readable colors on all daisyUI themes.  

There are 3 ways to override it:
- Using a utility class: https://play.tailwindcss.com/q6ggP42uRR
- In CSS:  https://play.tailwindcss.com/FUv3SBFOPB?file=css
- From theme config: https://play.tailwindcss.com/pK0nvomQH0?file=config
