### ISSUE TITLE
Daisy UI is failing to compiled if arbitrary values are used with the @apply directive during build

### ISSUE THREAD

**Issue by RafidMuhymin** [saadeghi/daisyui#814]
I'm using Daisy UI in a CRA app. But if I use arbitrary values with the `@apply` directive, Daisy UI is failing to compile during the build mode but it's working fine during the dev mode.

```scss
hr {
  @apply border-slate-300 border-[1.125px];
}

code {
  &::before {
    content: "`";
  }

  &::after {
    content: "`";
  }

  @apply text-[crimson];
}
```
