### ISSUE TITLE
feature request: dropdown-toggle version of dropdown

### ISSUE THREAD

**Issue by c-nv-s** [saadeghi/daisyui#872]
I noticed that none of the dropdown examples toggle off when you press the button again. ( and ``dropdown-hover`` didn't meet my requirement). 

I discovered this while attempting to create a toggling dropdown menu with the hamburger menu button from the ``swap`` section and realized it doesn't work: https://jsfiddle.net/ps9xt03w/ 

Is it possible to have dropdown-toggle that can work with the same hidden input as a swap button?

**Comment by c-nv-s** [comment]
gonna mention #824 here because I think that would also resolve that issue to.

**Comment by forgiv** [comment]
Not sure if this will help but this is how I handled toggling the dropdown.

Looks like this is the specific style that controls visibility for the dropdown content:
```CSS
.dropdown.dropdown-open .dropdown-content, 
.dropdown.dropdown-hover:hover .dropdown-content, 
.dropdown:not(.dropdown-hover):focus .dropdown-content, 
.dropdown:not(.dropdown-hover):focus-within .dropdown-content {
    visibility: visible;
    opacity: 1;
}
```

For my specific use case I don't need hover, I just wanted to be able to toggle the content visibility with a mouse click or keyboard event. So I added this CSS:

```CSS
#dropdown-content {
  visibility: hidden;
  opacity: 0;
}

.dropdown.dropdown-open #dropdown-content {
  visibility: visible;
  opacity: 1;
}
```

Then I just added click and keyup events to `div.dropdown` to toggle the `.dropdown-open` class and it works great.

My request would be to add a `.dropdown-toggle` class that allows the user to manually control visibility. 
I think just updating the visibility CSS from above with the `.dropdown-toggle` class would be enough:

```CSS
.dropdown.dropdown-open .dropdown-content, 
.dropdown.dropdown-hover:hover .dropdown-content, 
.dropdown:not(.dropdown-hover, .dropdown-toggle):focus .dropdown-content, 
.dropdown:not(.dropdown-hover, .dropdown-toggle):focus-within .dropdown-content {
    visibility: visible;
    opacity: 1;
}
```

Or something like that, IDK I'm not a CSS guru.
