### ISSUE TITLE
Change value of radial-progress bar through an attribute not css style

### ISSUE THREAD

**Issue by doingsomethingrandom** [saadeghi/daisyui#923]
It’s would make life a bit easier

the code right now in src/components/styled/radial-progress.css:
```css
.radial-progress {
  --value: 0;
  --size: 5rem;
  --thickness: calc(var(--size) / 10);
}
.radial-progress:after {
  @apply bg-current;
}
```

Right now you have set the value by doing this
```html
<div class="radial-progress" style="--value:70;">70%</div>
```

Could implement it like this:
```css
/* src/components/styled/radial-progress.css */
.radial-progress {
  /* --value: 0; */
  --value: attr(value);
  --size: 5rem;
  --thickness: calc(var(--size) / 10);
}
.radial-progress:after {
  @apply bg-current;
}
```
And use like this:
```html
<div class="radial-progress" value=“70”>70%</div>
```
but I don’t know what it would do if you don’t specify the value attribute

**Comment by doingsomethingrandom** [comment]
It’s would make life a bit easier

the code right now in src/components/styled/radial-progress.css:
```css
.radial-progress {
  --value: 0;
  --size: 5rem;
  --thickness: calc(var(--size) / 10);
}
.radial-progress:after {
  @apply bg-current;
}
```

how to use it:
```html
<div class="radial-progress" style="--value:70;">70%</div>
```

Could implement it like this i think:
```css
.radial-progress {
  --value: attr(value);
  --size: 5rem;
  --thickness: calc(var(--size) / 10);
}
