### ISSUE TITLE
Open tooltip only with tooltip-open

### ISSUE THREAD

**Issue by ncomendant** [saadeghi/daisyui#964]
I have a use-case where hovering should not open the tooltip, but instead have it open exclusively when the `tooltip-open` class is applied (regardless of if the element is hovered or not).

How should I accomplish this? I am currently adding/removing the `tooltip` class as needed, but as a result the fade transition is not working properly.

**Comment by SpaceCowboyMax** [comment]
My dumb solution is to create an opposite class of `tooltip-open`

```css
.tooltip.tooltip-hidden:after,
.tooltip.tooltip-hidden:before,
.tooltip:hover.tooltip-hidden:after,
.tooltip:hover.tooltip-hidden:before {
  opacity: 0;
  transition-delay: 75ms;
}
```
and then just toggle between them `tooltip-open` <--> `tooltip-hidden`
